---
sidebar: sidebar 
permalink: concept_vpi_manage_before.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, manage, managing 
summary: 在安裝及管理部署vCenter外掛程式之前、您需要執行幾項工作。 
---
= 開始之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在安裝及管理部署vCenter外掛程式之前、您需要執行幾項工作。



== 決定是否使用部署Web使用者介面或CLI

在大多數情況下、部署Web使用者介面是管理vCenter外掛程式時最方便的選項、本指南將說明此選項。不過、您也可以使用部署命令列介面來管理外掛程式。如需詳細資訊、請在部署CLI提示字元中輸入下列命令：

* 「部署外掛程式？」 （子命令包括：install、remove、show和update）
* 「顯示外掛程式套件」




== 所有管理工作的共同準備工作

無論管理工作為何、您都必須採取幾個步驟。一般準備工作包括：

* 請閱讀「使用入門」一節、以熟悉部署vCenter外掛程式。
* 確保ONTAP Select 安裝並執行了這個功能。如需詳細資訊、請參閱《VMware安裝與叢集部署指南》。
* 取得帳戶認證資料：
+
** 部署系統管理員帳戶
** vCenter伺服器帳戶


* 確保部署公用程式可透過網路存取vCenter伺服器的連接埠443。


視管理工作而定、可能需要額外的準備工作。



== 準備vCenter伺服器帳戶

在安裝及使用部署外掛程式之前、您必須以必要的權限建立vCenter帳戶。您可以建立具有所有必要權限的單一帳戶、或以單一權限建立多個帳戶。為簡化起見、以下範例將vCenter權限分散至三個不同的角色、然後將這些角色指派給三個對應的帳戶。



=== 驗證終端使用者對外掛程式的存取權

您需要一個帳戶、才能透過vSphere驗證外掛程式的存取權。帳戶必須具有下列vCenter權限：sessions.validate.session。在vCenter中建立帳戶之後、您必須將其定義至部署管理公用程式。在部署Web使用者介面中、按一下管理索引標籤、然後按一下認證、以提供vCenter伺服器位置和認證。

此帳戶的使用方式如下：

* 命名的vCenter伺服器會在外掛程式登錄對話方塊視窗中成為安裝目標。
* 部署會使用此帳戶來驗證vSphere使用者在安裝外掛程式後存取外掛程式的要求。




=== 管理外掛程式

在部署Web使用者介面中、您可以安裝外掛程式、然後進行升級或移除。每次執行其中一項管理動作時、系統都會在快顯視窗中提示您輸入vCenter帳戶。每個管理動作都是透過獨立的vCenter權限來控制。

若要安裝、升級及移除外掛程式、您必須指派下列權限：

* 擴充
+
** 登錄擴充
** 更新副檔名
** 取消登錄擴充




您可以建立單一角色和帳戶、並擁有全部三項權限、或視需要將權限分配給多個帳戶。



=== 存取外掛程式

終端使用者可透過vSphere存取外掛程式。您必須將下列權限指派給將使用外掛程式的帳戶：

* NetApp
+
** 部署ONTAP Select
+
*** 系統管理員





