---
sidebar: sidebar 
permalink: concept_adm_before.html 
keywords: administer, administering, web, before you begin 
summary: 建立ONTAP Select 完叢集後、您可以執行各種管理工作來支援部署。需要注意的一般考量有幾個。 
---
= 開始管理ONTAP Select 功能之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
建立ONTAP Select 完叢集後、您可以執行各種管理工作來支援部署。需要注意的一般考量有幾個。

一般而言、您可以使用部署Web介面執行的程序分為三類之一。

.部署ONTAP Select 一個叢集
您可以部署單一節點或多節點叢集。請參閱 link:task_deploy_cluster.html["部署ONTAP Select 一個叢集"] 以取得更多資訊。

.對現有ONTAP Select 的叢集執行程序
系統管理程序會依各種類別進行組織、例如_Security_和_Clusters_。

.在部署公用程式上執行程序
有幾個特定的部署程序（例如變更系統管理員密碼）。



== 管理 ONTAP Select

支援ONTAP Select 的過程包括許多不同的管理程序。此外、部署管理公用程式也有特定的程序。以下是其中最重要的程序。一般而言、全部都使用部署Web使用者介面。


NOTE: 您也可以 link:https://docs.netapp.com/us-en/ontap-select/task_cli_signing_in.html["使用命令列介面"] 管理 ONTAP Select 。



== 執行其他 ONTAP 組態

部署完一個叢集之後、您就可以設定及管理叢集、就像使用硬體型的作業系統一樣。ONTAP Select ONTAP例如、您可以使用 ONTAP 系統管理員或 ONTAP CLI 來設定 ONTAP Select 叢集。

.NetApp用戶端軟體
您可以ONTAP Select 使用下列支援的NetApp用戶端軟體連線至支援的解決方案：

* 系統管理程式ONTAP
* Active IQ Unified Manager
* OnCommand Insight
* OnCommand Workflow Automation
* SnapCenter
* 適用於VMware vSphere的虛擬儲存主控台


若要識別用戶端軟體的支援版本、請參閱 link:https://mysupport.netapp.com/matrix/["NetApp 互通性對照表工具"^]。如果用戶端軟體支援ONTAP SJ9、ONTAP Select 則相同版本也可支援該功能。


NOTE: 使用不必要的程式集和對應的外掛程式時、需要伺服器型授權。SnapCenter目前不支援使用支援的儲存系統SnapCenter 授權功能。ONTAP Select

不支援任何其他未列入清單的NetApp用戶端軟體ONTAP Select 。

.可能的組態選項
在設定叢集時、有幾種可用的選項、包括：

* 建立網路組態
* 配置您的集合體
* 建立資料儲存 VM （ SVM ）


.購買具有儲存容量的授權
如果您決定不安裝儲存容量的授權檔案、作為部署ONTAP Select 此叢集的一部分、則必須在使用購買授權執行的叢集寬限期到期之前、取得並安裝授權檔案。

.鏡射Aggregate
部署管理公用程式會從ONTAP Select 可用的資料存放區空間（例如Pool0和Pool1）、在每個節點上建立資料備援磁碟。若要在多節點叢集上實作資料的高可用度、您必須使用這些備援磁碟來建立鏡射Aggregate。
