---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: REST建立一套通用的技術和最佳實務做法、但每個API的詳細資料可能會因設計選項而異。在使用API之前、您應該先瞭解ONTAP Select 到「更新部署API」的詳細資料和操作特性。 
---
= ONTAP Select 部署 API 基本作業特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
REST建立一套通用的技術和最佳實務做法、但每個API的詳細資料可能會因設計選項而異。在使用API之前、您應該先瞭解ONTAP Select 到「更新部署API」的詳細資料和操作特性。



== Hypervisor主機與ONTAP Select 非節點

Hypervisor主機_是裝載ONTAP Select 一個整套虛擬機器的核心硬體平台。當在Hypervisor主機上部署及啟用某部支援的虛擬機器時、該虛擬機器被視為_這個節點_。ONTAP Select ONTAP Select在部署REST API的第3版中、主機和節點物件是分開且獨立的。這可建立一對多關係、讓一或多ONTAP Select 個支援節點可在同一個Hypervisor主機上執行。



== 物件識別碼

每個資源執行個體或物件在建立時都會指派一個唯一的識別碼。這些識別碼在ONTAP Select 特定的例子中是全域唯一的。在發出API呼叫以建立新的物件執行個體之後、相關的ID值會傳回HTTP回應的「位置」標頭中的呼叫者。您可以擷取識別碼、並在參照資源執行個體時用於後續通話。


NOTE: 物件識別碼的內容和內部結構可隨時變更。當您參照相關的物件時、只能視需要在適用的API呼叫上使用識別碼。



== 要求識別碼

每個成功的API要求都會指派一個唯一的識別碼。該識別碼會傳回相關HTTP回應的「quale-id」標頭中。您可以使用要求識別碼、統稱為單一特定API要求回應交易的活動。例如、您可以根據要求ID擷取交易的所有事件訊息。



== 同步和非同步呼叫

伺服器執行從用戶端接收的HTTP要求的主要方法有兩種：

* 同步伺服器會立即執行要求、並以200、201或204的狀態代碼回應。
* 非同步伺服器會接受要求、並以狀態代碼為202做出回應。這表示伺服器已接受用戶端要求、並開始執行背景工作以完成要求。最終成功或失敗無法立即取得、必須透過額外的API呼叫來判斷。




== 確認已完成長時間執行的工作

一般而言、任何可能需要很長時間才能完成的作業、都會使用伺服器的背景工作、以非同步方式處理。使用部署REST API時、每個背景工作都會以工作物件來鎖定、此工作物件會追蹤工作並提供資訊、例如目前狀態。工作物件（包括其唯一識別碼）會在建立背景工作之後、傳回HTTP回應中。

您可以直接查詢「工作」物件、以判斷相關聯的API呼叫是否成功。如需其他資訊、請參閱_使用工作物件進行非同步處理_。

除了使用「工作」物件之外、還有其他方法可以判斷要求是否成功、包括：

* 事件訊息您可以使用原始回應傳回的要求ID、擷取與特定API呼叫相關的所有事件訊息。事件訊息通常包含成功或失敗的指示、也可在偵錯錯誤條件時使用。
* 資源狀態或狀態數個資源會保留狀態或狀態值、您可以查詢這些值、間接判斷要求的成功或失敗。




== 安全性

部署API使用下列安全技術：

* 傳輸層安全所有透過網路在部署伺服器與用戶端之間傳送的流量都會透過TLS加密。不支援在未加密的通道上使用HTTP傳輸協定。支援TLS 1.2版。
* HTTP驗證基本驗證適用於每個API交易。每個要求都會新增一個HTTP標頭、其中包含基礎64字串中的使用者名稱和密碼。

