---
sidebar: sidebar 
permalink: concept_vpi_planning.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, planning 
summary: 在安裝及使用部署vCenter外掛程式之前、您應該做好準備、以確保成功。 
---
= 規劃使用部署vCenter外掛程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在安裝及使用部署vCenter外掛程式之前、您應該做好準備、以確保成功。



== 軟體需求

下表說明幾項軟體需求、您應該加以考量。

[cols="35,65"]
|===
| 軟體 | 支援的版本 


| 部署公用程式ONTAP Select | 2.11.2或更新版本 


| VMware vSphere | 6.5 GA或更新版本 


| VMware vSphere使用者介面 | HTML5（不支援Flash版本） 


| ESXi | 6.5U2或更新版本 
|===


== 叢集大小限制

下表說明與叢集大小有關的限制、您應該考慮這些限制。

[cols="35,65"]
|===
| 項目 | 支援的上限 


| 部署叢集ONTAP Select | 100 


| 節點（虛擬機器） | 1000 


| 主機 | 800 
|===


== vCenter使用者帳戶的RBAC權限

管理及存取外掛程式需要幾種不同的vCenter權限。這些權限對應於下列三種類別的動作：

* 透過部署來管理外掛程式：
+
** 安裝
** 升級
** 移除


* 透過vSphere用戶端存取外掛程式
* 透過vSphere驗證使用者對外掛程式的存取權


請參閱 link:concept_vpi_manage_before.html#preparing-the-vcenter-server-accounts["準備vCenter伺服器帳戶"] 以取得更多資訊。



== 部分限制AutoSupport

部署vCenter外掛程式可在部署管理公用程式（包括外掛程式URL）中提供最低使用量資訊。不過AutoSupport 、這個功能確實包含一個已安裝外掛程式的表格、可透過AutoSupport 這個檢視器顯示。


NOTE: 您無法AutoSupport 使用部署外掛程式透過vSphere Web用戶端下載更新套件。您必須使用原生部署介面來下載AutoSupport 更新套件。



== 其他限制

在安裝及使用部署vCenter外掛程式之前、您還需要考量其他幾項限制：

* vCenter外掛程式的每個執行個體僅支援一部vCenter伺服器。
* 不支援以連結模式設定的vCenter伺服器。
* vSphere中的部署外掛程式GUI只會顯示叢集、ONTAP Select 其中包含由相同vCenter伺服器管理的VMware虛擬機器。不含在獨立式ESXi和KVM主機上執行的VMware叢集。ONTAP Select

