---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, capacity pools, operation details 
summary: 容量資源池授權模式與容量層模式不同。儲存容量會分配給一個集區、並在許多節點之間共用、而非將儲存容量專用於每個個別節點。已建立其他元件和程序來支援容量集區模式。 
---
= ONTAP Select 容量資源池授權模式的營運詳細資料
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量資源池授權模式與容量層模式不同。儲存容量會分配給一個集區、並在許多節點之間共用、而非將儲存容量專用於每個個別節點。已建立其他元件和程序來支援容量集區模式。



== 授權管理員

使用許可管理員會在部署管理公用程式的每個執行個體內以個別程序執行。LM提供的部分功能包括：

* 根據容量集區授權序號、為每個節點產生唯一的二十位數序號
* 根據ONTAP Select 來自各個節點的要求、從共享容量資源池建立容量租賃
* 透過部署使用者介面回報集區使用資訊




== 租賃特性

在使用容量資源池授權的節點上、為每個資料集合分配的儲存設備必須具有相關的租賃。節點要求儲存設備租賃、如果容量可用、則授權管理員會以租賃回應。每個租期都有下列明確或隱含的屬性：

* License Manager每ONTAP Select 個節點都與一個License Manager執行個體相關聯
* 容量資源池每ONTAP Select 個節點都與一個容量資源池相關聯
* 儲存設備配置會在租賃中指派特定容量值
* 到期日與時間租賃的期間介於1小時到7天之間、視使用者組態而定。




== 授權鎖定ID

每個使用許可管理員執行個體、以及每個對應的部署公用程式執行個體、都會以唯一的128位元號碼來識別。此數字與九位數容量資源池授權序號結合使用、可將資源池鎖定至特定的授權管理員執行個體（實際上是部署執行個體）。您必須在NetApp支援網站上提供這兩個值、作為產生NetApp授權檔案（NLF）的一部分。

您可以使用Web使用者介面、以下列方式判斷部署執行個體的授權鎖定ID：

* 「快速入門」頁面此頁面會在您第一次登入部署時顯示。您也可以按一下頁面右上角的下拉式方塊、然後選取「Getting Started（使用入門）」、以顯示頁面。LLID會顯示在「新增授權」區段中。
* 系統管理按一下頁面頂端的「*管理*」索引標籤、然後按一下「*系統*」和「*設定*」。




== 基本租賃作業

每次建立、擴充或變更資料Aggregate時、均必須尋找或申請有效的容量租用。ONTAP Select您可以使用從先前的申請中取得且仍有效的租賃、或視需要申請新的租賃。下列步驟是ONTAP Select 由節點執行、以找出容量資源池租賃：

. 如果節點上有現有的租用、則只要符合下列所有條件、就會使用該租用：
+
** 租約尚未到期
** 集合體的儲存要求不會超過租用容量


. 如果找不到現有的租用、節點會向授權管理員要求新的租用。




== 將儲存容量傳回容量集區

儲存容量會視需要從容量資源池中分配、而每個新要求都會減少資源池中的可用儲存空間。儲存容量會在多種情況下傳回集區、包括：

* 資料Aggregate的租期將會到期、且節點不會續約
* 刪除資料Aggregate



NOTE: 如果刪除某部執行中的虛擬機器、則所有執行中的租賃將一直有效、直到到期為止。ONTAP Select發生這種情況時、容量會傳回集區。
