---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: 內部ONTAP Select 和外部的不二網路特性。 
---
= ONTAP Select 內部和外部網路
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
內部和外部網路的特性ONTAP Select 。



== 內部網路ONTAP Select

內部 ONTAP Select 網路僅存在於該產品的多節點版本中，負責為 ONTAP Select 叢集提供叢集通訊、HA 互連和同步複寫服務。此網路包含以下連接埠和介面：

* * e0c、e0d.*託管叢集網路lifs
* * e0e.*託管RSMLIF
* *主控HA互連LIF的e0f.*


此網路的處理量和延遲對於判斷ONTAP Select 叢集的效能和恢復能力至關重要。叢集安全性需要網路隔離、並確保系統介面與其他網路流量分開。因此ONTAP Select 、此網路必須專供該叢集使用。


NOTE: 不支援針對Select叢集流量以外的流量使用Select內部網路、例如應用程式或管理流量。在不支援內部VLAN的ONTAP 情況下、不可能有其他VM或主機。

流經內部網路的網路封包必須位於專屬的VLAN標記層2網路上。您可以完成下列其中一項工作來完成這項工作：

* 將VLAN標記的連接埠群組指派給內部虛擬NIC（e0c到e0f）（VST模式）
* 使用上游交換器所提供的原生VLAN、而原生VLAN不用於任何其他流量（指派沒有VLAN ID的連接埠群組、亦即、EST模式）


在任何情況下、內部網路流量的VLAN標記都是在ONTAP Select 不屬於該虛擬機器的情況下進行。


NOTE: 僅支援 ESXi 標準和分散式 vSwitches。不支援其他虛擬交換器或 ESXi 主機之間的直接連線。內部網路必須完全開放；不支援 NAT 或防火牆。

在ONTAP Select叢集中，內部流量和外部流量使用稱為連接埠群組的虛擬二層網路物件進行隔離。正確分配這些連接埠群組的 vSwitch 非常重要，尤其是對於負責提供叢集、HA 互連和鏡像複製服務的內部網路而言。這些網路連接埠的網路頻寬不足會導致效能下降，甚至影響叢集節點的穩定性。因此，4、6、8、10 和 12 節點叢集要求內部ONTAP Select網路使用 10Gb 連線；不支援 1Gb 網路卡。不過，可以對外部網路做出權衡，因為限制傳入ONTAP Select叢集的資料流量不會影響其可靠運作的能力。

雙節點叢集可使用四個1Gb連接埠進行內部流量、或使用單一10Gb連接埠、而非四節點叢集所需的兩個10Gb連接埠。在無法容納四張10Gb NIC卡的環境中、內部網路可使用兩張10Gb NIC卡、外部ONTAP 的支援網卡則可使用兩個1Gb NIC。



=== 內部網路驗證與疑難排解

可以使用網路連接檢查器功能來驗證多節點叢集的內部網路。此功能可以透過在 Deploy CLI 中執行  `network connectivity-check start` 命令來呼叫。

執行下列命令以檢視測試的輸出：

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
此工具僅適用於排查多節點 Select 叢集的內部網路故障。此工具不應用於排查單節點叢集（包括 vNAS 組態）、 ONTAP Deploy 與 ONTAP Select 連線問題或用戶端連線問題。

叢集建立精靈（ ONTAP Deploy 使用者介面的一部分）包含內部網路檢查器，作為建立多節點叢集期間的可選步驟。鑑於內部網路在多節點叢集中扮演的重要角色，將此步驟納入叢集建立工作流程可以提高叢集建立操作的成功率。

從ONTAP 推出《2000年2月10日之際、內部網路所使用的MTU大小可設定在7、500到9、000之間。網路連線檢查工具也可用來測試7、500到9、000之間的MTU尺寸。預設的MTU值會設為虛擬網路交換器的值。如果環境中存在類似VXLAN的網路覆蓋、則必須以較小的值取代該預設值。



== 外部網路ONTAP Select

ONTAP Select 外部網路負責叢集的所有出站通訊，因此在單節點和多節點組態中都存在。雖然此網路不像內部網路那樣具有嚴格定義的處理量需求，但管理員應小心避免在用戶端與 ONTAP VM 之間造成網路瓶頸，因為效能問題可能會被誤判為 ONTAP Select 問題。


NOTE: 外部流量可在vSwitch層（VST）和外部交換器層（EST）標記、方式與內部流量類似。此外、ONTAP Select 在稱為VGT的程序中、可透過不受影響的VM本身來標記外部流量。請參閱一節 link:concept_nw_data_mgmt_separation.html["資料與管理流量分離"] 以取得更多詳細資料。

下表重點說明ONTAP Select 內部和外部網路之間的主要差異。

*內部與外部網路快速參考*

[cols="3*"]
|===
| 說明 | 內部網路 | 外部網路 


| 網路服務 | 叢集HA/IC RAID SyncMirror 功能（RSM） | 資料管理叢集間（SnapMirror和SnapVault SnapMirror） 


| 網路隔離 | 必要 | 選用 


| 框架大小（MTU） | 7、500至9、000 | 1、500（預設）9、000（支援） 


| IP位址指派 | 自動產生 | 使用者定義 


| DHCP支援 | 否 | 否 
|===


=== NIC群組

為了確保內部和外部網路具備必要的頻寬和恢復特性、以提供高效能和容錯能力、建議使用實體網路介面卡群組。支援具有單一10Gb連結的雙節點叢集組態。不過、NetApp建議的最佳實務做法是在ONTAP Select 內部和外部網路上使用NIC群組、



=== MAC位址產生

指派給ONTAP Select 所有「資訊區」網路連接埠的MAC位址會由隨附的部署公用程式自動產生。此公用程式使用NetApp專屬的平台專屬、組織專屬的識別碼（OUI）、以確保FAS 不會與任何系統發生衝突。然後、此位址的複本會儲存在ONTAP Select 內部資料庫中的安裝VM ONTAP （簡稱「整合」）中、以避免在未來的節點部署期間意外重新指派。管理員絕不能修改網路連接埠的指定MAC位址。
