---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: 首先熟悉ONTAP Select 適用於整個過程的一般網路概念。然後探索單一節點和多節點叢集的特定特性和選項。 
---
= 網路：一般概念與特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
首先熟悉ONTAP Select 適用於整個過程的一般網路概念。然後探索單一節點和多節點叢集的特定特性和選項。



== 實體網路

實體網路主要透過ONTAP Select 提供底層的第二層交換基礎架構、來支援叢集式部署。與實體網路相關的組態包括Hypervisor主機和更廣泛的交換式網路環境。



=== 主機NIC選項

每ONTAP Select 個物件Hypervisor主機都必須設定兩個或四個實體連接埠。您選擇的確切組態取決於多種因素、包括：

* 叢集是否包含一個或多ONTAP Select 個支援主機
* 所使用的Hypervisor作業系統
* 虛擬交換器的設定方式
* LACP是否與鏈路一起使用




=== 實體交換器組態

您必須確定實體交換器的組態支援ONTAP Select 進行物件部署。實體交換器與Hypervisor型虛擬交換器整合。您選擇的確切組態取決於多種因素。主要考量包括：

* 您要如何在內部和外部網路之間保持區隔？
* 您是否會在資料與管理網路之間保持區隔？
* 如何設定第二層VLAN？




== 邏輯網路

使用兩個不同的邏輯網路、根據類型來分隔流量。ONTAP Select具體而言、流量可在叢集內的主機之間、以及儲存用戶端和叢集外的其他機器之間流通。Hypervisor管理的虛擬交換器有助於支援邏輯網路。



=== 內部網路

透過多節點叢集部署、個別ONTAP Select 的元集節點會使用隔離的「內部」網路進行通訊。此網路不會在ONTAP Select 叢集節點外曝光或可用。


NOTE: 內部網路僅存在於多節點叢集。

內部網路具有下列特性：

* 用於處理ONTAP 叢集內的各種流量、包括：
+
** 叢集
** 高可用度互連（HA-IC）
** RAID同步鏡射（RSM）


* 單一第二層網路、以VLAN為基礎
* 靜態IP位址是由ONTAP Select 下列項目指派：
+
** 僅限IPV4
** 未使用DHCP
** 連結本機位址


* MTU大小預設為9000位元組、可在7500-9000範圍內調整（含）




=== 外部網路

外部網路負責處理ONTAP Select VMware叢集節點與外部儲存用戶端及其他機器之間的流量。外部網路是每個叢集部署的一部分、具有下列特性：

* 用於處理ONTAP 不順暢的流量、包括：
+
** 資料（NFS、CIFS、iSCSI）
** 管理（叢集與節點；選用SVM）
** 叢集間（選用）


* （可選）支援VLAN：
+
** 資料連接埠群組
** 管理連接埠群組


* 根據管理員的組態選項指派的IP位址：
+
** IPV4或IPV6


* MTU大小預設為1500位元組（可調整）


外部網路存在各種規模的叢集。



== 虛擬機器網路環境

Hypervisor主機提供多項網路功能。

透過虛擬機器展示下列功能：ONTAP Select

虛擬機器連接埠:: 有多個連接埠ONTAP Select 可供使用。它們是根據多種因素（包括叢集大小）來指派和使用。
虛擬交換器:: Hypervisor環境中的虛擬交換器軟體（無論是vSwitch（VMware）或開放式vSwitch（KVM））、都會將虛擬機器公開的連接埠與實體乙太網路NIC連接埠結合在一起。您必須根據ONTAP Select 環境、為每個支援的主機設定vSwitch。

