---
sidebar: sidebar 
permalink: concept_stor_eff_support.html 
keywords: ontap select, storage efficiency support 
summary: 提供的儲存效率選項類似於介紹在功能性和功能性上的儲存效率選項。ONTAP Select FAS AFF 
---
= 儲存效率支援
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
提供的儲存效率選項類似於介紹在功能性和功能性上的儲存效率選項。ONTAP Select FAS AFF

使用All Flash VSAN或一般Flash陣列進行的虛擬NAS（vNAS）部署、應遵循非SSD DAS儲存設備的最佳實務做法。ONTAP Select ONTAP Select

只要您有具備SSD磁碟機和Premium授權的DAS儲存設備、就會在新安裝中自動啟用AFF型特性設定。

有了AFF般的特性設定、下列即時SE功能會在安裝期間自動啟用：

* 即時零模式偵測
* Volume內嵌重複資料刪除技術
* Volume背景重複資料刪除技術
* 可調適的即時壓縮
* 即時資料精簡
* 集合體即時重複資料刪除技術
* Aggregate背景資料刪除技術


若要驗ONTAP Select 證是否已啟用所有預設的儲存效率原則、請在新建立的磁碟區上執行下列命令：

[listing]
----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

NOTE: 若要從9.4升級、您必須在具有Premium授權的DAS SSD儲存設備上安裝才能使用的更新版本。ONTAP Select ONTAP Select此外、在使用ONTAP 「支援」功能進行叢集初始安裝期間、必須勾選「*啟用儲存效率*」核取方塊。如果在未符合先前條件的情況下啟用AFF型特性設定ONTAP後升級、則需要手動建立開機引數和節點重新開機。如需詳細資訊、請聯絡技術支援部門。

下表摘要列出各種可用的儲存效率選項、預設為啟用、或預設為未啟用、但建議使用、視ONTAP Select 乎版本和媒體類型而定。

[cols="6"]
|===
| 功能ONTAP Select | 9.6 / 9.5 Premium或Premium XL^4^（DAS SSD） | 9.4^1^/ 9.3^2^高級版（DAS SSD） | 9.6 / 9.5 / 9.4 / 1^/ 9.3 / 2^所有授權（DAS HDD） | 9.6所有授權（vNAS） | 9.5 / 9.4^1^/ 9.3^2^高級版或標準版（vNAS）^3^ 


| 即時零偵測 | 是（預設） | 是、由使用者以每個磁碟區為基礎來啟用 | 是、由使用者以每個磁碟區為基礎來啟用 | 是、由使用者以每個磁碟區為基礎來啟用 | 不支援 


| Volume內嵌重複資料刪除技術 | 是（預設） | 是（建議）由使用者以每個Volume為基礎來啟用 | 無法使用 | 不支援 | 不支援 


| 32K即時壓縮（二線壓縮） | 是、由使用者在每個磁碟區基礎上啟用。 | 是、由使用者以每個磁碟區為基礎來啟用 | 是、由使用者以每個磁碟區為基礎來啟用 | 不支援 | 不支援 


| 8K內嵌壓縮（調適性壓縮） | 是（預設） | 是（建議）由使用者以每個Volume為基礎來啟用 | 是、由使用者在每個磁碟區基礎上啟用 | 不支援 | 不支援 


| 背景壓縮 | 不支援 | 不支援 | 是、由使用者在每個磁碟區基礎上啟用 | 是、由使用者以每個磁碟區為基礎來啟用 | 不支援 


| 壓縮掃描儀 | 是的 | 是、由使用者以每個磁碟區為基礎來啟用 | 是的 | 是、由使用者以每個磁碟區為基礎來啟用 | 不支援 


| 即時資料精簡 | 是（預設） | 是（建議）由使用者以每個Volume為基礎來啟用 | 是、由使用者在每個磁碟區基礎上啟用 | 不支援 | 不支援 


| 壓實掃描器 | 是的 | 是、由使用者以每個磁碟區為基礎來啟用 | 是的 | 不支援 | 不支援 


| 集合體即時重複資料刪除技術 | 是（預設） | 是（建議）、由使用者以每個磁碟區為單位啟用、空間保證=無） | 不適用 | 不支援 | 不支援 


| Volume背景重複資料刪除技術 | 是（預設） | 是（建議） | 是、由使用者在每個磁碟區基礎上啟用 | 是、由使用者以每個磁碟區為基礎來啟用 | 不支援 


| Aggregate背景資料刪除技術 | 是（預設） | 是（建議）、由使用者以每個磁碟區為單位啟用、空間保證=無） | 不適用 | 不支援 | 不支援 
|===
DAS SSD上的[Small（小型）#1^ONTAP Select 9.4（需要Premium授權）允許使用Aggregate層級背景跨Volume掃描器來刪除Aggregate中的現有資料。這項一次性作業是針對在DAS SSD上建立9.4之前的磁碟區手動執行的。#[Small ]#^2^ONTAP Select 9.3（需要Premium授權）支援集合體層級的背景重複資料刪除；不過、建立集合體之後必須啟用此功能。#[Small ]#^3^ONTAP Select 9.5 vNAS預設不支援任何儲存效率原則。請參閱vNAS一節、以取得單一執行個體資料記錄（SIDL）的詳細資料。#[Small（小）#^4^ONTAP Select 9.6支援新的授權（Premium XL）和新的VM大小（大）。不過、大型VM僅支援使用軟體RAID的DAS組態。目前ONTAP Select 版本中的大型版不支援硬體RAID和vNAS組態。#

升級ONTAP Select 至版本S區時、請等待「系統節點升級還原show」命令、表示升級已完成、然後再驗證現有磁碟區的儲存效率值。

在升級至ONTAP Select 版本為NetApp 9.5或更新版本的系統上、在現有集合體或新建立的集合體上建立的新磁碟區、其行為與在全新部署上建立的磁碟區相同。進行ONTAP Select 程式碼更新的現有磁碟區、與新建立的磁碟區具有大部分相同的儲存效率原則、但有一些差異：

案例1:: 如果在升級之前未在磁碟區上啟用任何儲存效率原則、則：
+
--
* 具有「最快保證= Volume」的磁碟區並未啟用即時資料壓縮、集合式即時重複資料刪除、以及集合式背景重複資料刪除功能。這些選項可在升級後啟用。
* 具有「sh步調 保證=無」的Volume並未啟用背景壓縮。此選項可在升級後啟用。
* 現有磁碟區上的儲存效率原則會設定為在升級後自動執行。


--
案例2:: 如果在升級之前、某個磁碟區已啟用部分儲存效率、則：
+
--
* 「最快保證= Volume」的磁碟區在升級後沒有任何差異。
* 具有「最快保證=無」的磁碟區會開啟Aggregate背景重複資料刪除功能。
* 具有「僅限即時原則」的磁碟區會將其原則設為自動。
* 使用者定義儲存效率原則的磁碟區在原則上沒有變更、但「最快保證=無」的磁碟區除外。這些磁碟區已啟用Aggregate背景重複資料刪除功能。


--


升級至ONTAP Select 版本S9.5或更新版本之後、將保留升級之前啟用的儲存效率功能。如果在升級之前未啟用儲存效率、則不會在升級後啟用儲存效率。
