---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: 部署ONTAP Select 完一個叢集後、您可以ONTAP 使用標準ONTAP 的更新程序、視需要升級每個節點的ImageImage。 
---
= 升級 ONTAP Select 節點
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
部署ONTAP Select 完一個叢集後、您可以ONTAP 視需要在叢集中的每個節點上升級該鏡像。


CAUTION: 您無法使用部署管理公用程式來升級現有ONTAP Select 的各個節點。部署公用程式只能用來建立新ONTAP Select 的叢集。



== 一般程序

在較高層級、您應該使用下列步驟來升級現有ONTAP Select 的節點。

. 瀏覽至NetApp支援網站的下載頁面。
+
https://mysupport.netapp.com/site/downloads["NetApp支援下載"^]

. 按一下「* ONTAP Select 不含節點升級*」。
. 選取並下載適當的升級映像、視需要回應所有提示。
+
在升級ONTAP Select 一個節點之前、請檢閱版本說明以取得更多資訊和任何必要程序。

. 使用ONTAP Select 標準ONTAP 的升級程序、透過ONTAP Select 升級檔升級到這個節點。如需 ONTAP 升級程序的詳細資訊、包括支援的升級路徑等資訊、請參閱 link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP 升級總覽"^]。




== 還原 ONTAP Select 節點

您無法將 ONTAP Select 節點還原為原先安裝的版本。例如：

ONTAP Select 9.7 一開始即已安裝:: 您可以將節點升級至 9.8 版、然後視需要還原至 9.7 版。
ONTAP Select 9.8 一開始即已安裝:: 您無法還原至 9.7 版、因為此版本早於原本安裝的版本。




== 使用 VMXNET3 網路驅動程式

VMXNET3 是 VMware ESXi 上新叢集部署所隨附的預設網路驅動程式。如果您升級執行 ONTAP Select 9.4 或更早版本的現有 ONTAP Select 節點、則不會自動升級網路驅動程式。您必須手動升級至VMXNET3。如需升級協助、請聯絡NetApp支援部門。
