---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: 部署具有HA的雙節點叢集時、必須使用與其他叢集節點組態相同的規劃與組態。不過、在建立雙節點叢集時、您應該注意幾個差異。 
---
= 使用HA的雙節點叢集ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
部署具有HA的雙節點叢集時、必須使用與其他叢集節點組態相同的規劃與組態。不過、在建立雙節點叢集時、您應該注意幾個差異。

.目標環境
雙節點叢集由一組HA配對組成、專為遠端辦公室和分公司部署所設計。


NOTE: 雖然主要是針對遠端和分公司環境所設計、但您也可以視需要在資料中心內部署雙節點叢集。

.授權
您可以使用任何VMware vSphere授權來部署雙節點叢集。不過、VMware ROBO標準與進階授權是遠端與分公司部署的理想選擇。

.中介服務
當叢集由兩個節點組成時、當節點故障或失去通訊時、就無法達到所需的仲裁量。為了解決這些類型的腦分割情況、ONTAP Select 每個執行個體的示例都包含一個中介服務。此服務會連線至作用中雙節點叢集中的每個節點、以監控HA配對並協助管理故障。中介服務會在每個雙節點叢集相關的專用iSCSI目標上維護HA狀態資訊。


CAUTION: 如果您有一個或多個作用中的雙節點叢集、ONTAP Select 則管理叢集的「部署」虛擬機器必須隨時執行。如果部署虛擬機器停止或故障、則無法使用中介服務、而且雙節點叢集的HA功能也會遺失。

.叢集和中介服務的位置
由於雙節點叢集通常部署在遠端或分公司、因此它們可以遠端從公司資料中心部署、而部署公用程式則提供管理支援。使用此組態、部署公用程式與叢集之間的管理流量會透過WAN傳輸。如需限制與限制的詳細資訊、請參閱版本說明。

.備份部署組態資料
最佳做法是定期備份部署組態資料、包括在建立叢集之後。這對雙節點叢集而言特別重要、因為備份中包含了中介組態資料。

.指派給部署的靜態IP位址
您必須為部署管理公用程式指派靜態IP位址。此需求適用於管理一ONTAP Select 或多個雙節點叢集的所有部署執行個體。
