---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: 在規劃安裝ONTAP Select 此功能時、您應該考慮幾項一般需求。 
---
= 部署一般需求與規劃ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在規劃安裝ONTAP Select 此功能時、您應該考慮幾項一般需求。



== 將部署公用程式與ONTAP Select 整個叢集配對

您可以在將部署公用程式的執行個體與ONTAP Select 叢集配對時、使用多種選項。


NOTE: 在所有部署案例中、只ONTAP Select 有一個部署管理公用程式執行個體可以管理單一的叢集和叢集中的節點。叢集無法由部署公用程式的兩個或多個不同執行個體來管理。

.每ONTAP Select 個叢集的公用程式執行個體
您可以ONTAP Select 使用部署公用程式的專屬執行個體來部署和管理每個叢集。有了這種一對一組態、每個公用程式對叢集配對之間都有明確的區隔。此組態可提供較小故障網域的高層級隔離。

.一個公用程式執行個體可用於多ONTAP Select 個實體叢集
您可以ONTAP Select 使用單一部署公用程式執行個體、在組織中部署及管理多個支援叢集。有了這種一對多組態、所有的處理和組態資料都是由部署公用程式的同一個執行個體來管理。


NOTE: 部署公用程式的一個執行個體最多可管理400 ONTAP Select 個節點或100個叢集。



== 與 KVM 環境相關的需求

在 KVM Hypervisor 環境中安裝部署管理公用程式之前、您應該先檢閱基本需求、然後準備部署。

.部署的需求與限制
在 KVM 環境中安裝 ONTAP Select 部署公用程式時、您應該考慮幾項需求和限制。

.Linux KVM 主機伺服器硬體需求
您的 Linux KVM Hypervisor 主機必須符合數項最低資源需求。確認部署 ONTAP Select 的主機符合下列基本需求：

* Linux 伺服器：
+
** 硬體和軟體必須為 64 位元
** 伺服器必須遵守為 ONTAP Select 節點所定義的相同支援版本


* 虛擬CPU（2個）
* 虛擬記憶體（ 4GB ）
* 儲存設備（ 40GB ）
* " 動態主機組態傳輸協定（ DHCP ）已啟用（您也可以指派靜態 IP 位址）


.網路連線能力
確認已設定部署虛擬機器網路介面、並可連線至其管理的 ONTAP Select 主機。

.支援IP版本4
僅支援IP第4版（IPV4）ONTAP Select 。不支援IP版本6（IPv6）。此限制會以ONTAP Select 下列方式影響到流通：

* 您必須將 IPv4 位址指派給部署 VM 的管理 LIF 。
* 「部署」無法建立ONTAP Select 設定為在ONTAP 整個過程中使用IPv6的動態節點。




== 必要的組態資訊

在您的部署規劃中、您應該先判斷必要的組態資訊、然後再安裝ONTAP Select 「整合部署」管理公用程式。

.部署 VM 的名稱
用於 VM 的名稱。

.Linux KVM 主機名稱
安裝部署公用程式的 Linux KVM 主機。

.儲存池名稱
存放 VM 檔案的儲存池（約需 40GB ）。

.虛擬機器的網路
連接部署 VM 的網路。



== 選用的網路組態資訊

部署虛擬機器預設是使用 DHCP 進行設定。不過、如果需要、您可以手動設定 VM 的網路介面。

.主機名稱
主機名稱。

.主機IP位址
靜態 IPv4 位址。

.子網路遮罩
子網路遮罩、以 VM 所屬的網路為基礎。

.閘道
預設閘道或路由器。

.主要DNS伺服器
主要網域名稱伺服器。

.次要DNS伺服器
次要網域名稱伺服器。

.搜尋網域
要使用的搜尋網域。



== 使用認證儲存區進行驗證

ONTAP Select Deploy 認證儲存區是儲存帳戶資訊的資料庫。部署會使用帳戶認證來執行主機驗證、做為叢集建立與管理的一部分。您應該瞭解認證儲存區如何在規劃ONTAP Select 還原部署時使用。


NOTE: 帳戶資訊會使用AES加密演算法和SHA-256雜湊演算法、安全地儲存在資料庫中。

.認證類型
支援下列類型的認證：

* 用於驗證Hypervisor主機的主機、做為將ONTAP Select VMware ESXi節點直接部署至VMware ESXi的一部分
* vCenter用於驗證vCenter伺ONTAP Select 服器、以在VMware vCenter管理主機時、將VMware節點部署至ESXi


.存取
認證存放區是在內部存取、做為使用部署執行一般管理工作的一部分、例如新增Hypervisor主機。您也可以透過部署Web使用者介面和CLI直接管理認證存放區。
