---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: 支援大部分的功能。ONTAP Select ONTAP部署叢集時、會自動為每個節點授權許多功能。ONTAP不過、有些功能需要另一份授權。 
---
= ONTAP Select 支援 ONTAP 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
支援大部分的功能。ONTAP Select ONTAP部署叢集時、會自動為每個節點授權許多功能。ONTAP不過、有些功能需要另一份授權。


NOTE: 通常不支援含有硬體相依性的支援功能。ONTAP ONTAP Select



== 根據預設會自動啟用的支援功能ONTAP

ONTAP Select 支援下列 ONTAP 功能，並依預設授權：

* 自主勒索軟體保護（ ARP ）（手動更新）
* CIFS
* 重複資料刪除與壓縮
* FlexCache
* FlexClone
* iSCSI
* NDMP
* NetApp Volume Encryption（僅限非受限國家/地區）
* NFS
* NVMe over TCP
* 支援多租戶共享ONTAP
* SS3 ONTAP
* S3 SnapMirror
* SnapMirror
* SnapMirror雲
* SnapRestore
* SnapVault
* 儲存 VM 災難恢復（ SVM DR ）
+

NOTE: ONTAP Select 支援 SVM DR 做為來源和目的地，最多可與 16 個關係。SVM DR 支援僅限於使用來源 ONTAP 版本至版本 +2 。例如、 ONTAP Select 9.12.1 來源可以連線至目的地 ONTAP 9.12.1 、 9.13.1 或 9.14.1 版。





== 個別授權的功能ONTAP

您必須針對ONTAP 預設未啟用的任何功能取得個別授權、包括：

* FabricPool
* SDS（不含高級授權）MetroCluster ONTAP Select
* SnapLock Enterprise for ONTAP Select 9.16.1 及更早版本（可從link:https://mysupport.netapp.com/site/["NetApp 支援網站"^])
+

NOTE: ONTAP Select不支援SnapLock Compliance 。

+
** 可防竄改的Snapshot複本


* SnapLock Select



NOTE: 使用 StorageGRID 時不需要 FabricPool 授權。

.相關資訊
* link:concept_ots_overview.html#comparing-ontap-select-and-ontap-9["比較功能與功能ONTAP Select ONTAP"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["NetApp ONTAP -主要授權金鑰"^]

