---
sidebar: sidebar 
permalink: reference_api_workflow.html 
keywords: rest api, deploy rest api, rest, workflow, create cluster, curl, json 
summary: 您可以在由 vCenter 管理的 VMware ESXi 主機上部署單節點 ONTAP Select 叢集。 
---
= 在 ESXi 上建立 ONTAP Select 單節點評估叢集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在ONTAP Select 由vCenter管理的VMware ESXi主機上部署單節點的VMware ESXi叢集。叢集是以評估授權所建立。

叢集建立工作流程在下列情況下有所不同：

* ESXi 主機不受 vCenter（獨立式主機）代管。
* 叢集中使用多個節點或主機。
* 叢集已部署在正式作業環境中，並搭配已購買的授權。
* 使用 KVM Hypervisor 取代 VMware ESXi。




[[step-1-register-vcenter-server-credential]]
== 步驟 1：註冊 vCenter 伺服器認證資料

部署至由 vCenter 伺服器代管的 ESXi 主機時，您必須在註冊主機之前新增認證資料。然後，Deploy 管理公用程式即可使用該認證資料向 vCenter 進行驗證。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 部署 | 貼文 | /安全性/認證 
|===
捲髮::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step01 'https://10.21.191.150/api/security/credentials'
----
Json輸入（步驟01）::


[source, json]
----
{
  "hostname": "vcenter.company-demo.com",
  "type": "vcenter",
  "username": "misteradmin@vsphere.local",
  "password": "mypassword"
}
----
處理類型:: 非同步
輸出::
+
--
* 位置回應標頭中的認證ID
* 工作物件


--




[[step-2-register-a-hypervisor-host]]
== 步驟 2：註冊 Hypervisor 主機

新增一個 Hypervisor 主機，其中包含 ONTAP Select 節點的虛擬機器將在該主機上執行。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 叢集 | 貼文 | /主機 
|===
捲髮::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step02 'https://10.21.191.150/api/hosts'
----
Json輸入（步驟02）::


[source, json]
----
{
  "hosts": [
    {
      "hypervisor_type": "ESX",
      "management_server": "vcenter.company-demo.com",
      "name": "esx1.company-demo.com"
    }
  ]
}
----
處理類型:: 非同步
輸出::
+
--
* 位置回應標頭中的主機ID
* 工作物件


--




[[step-3-create-a-cluster]]
== 步驟 3：建立叢集

建立 ONTAP Select 叢集時，基本叢集組態會被註冊，Deploy 會自動產生節點名稱。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 叢集 | 貼文 | /叢集 
|===
捲髮:: 對於單節點叢集，應將查詢參數 node_count 設定為 1。


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step03 'https://10.21.191.150/api/clusters? node_count=1'
----
Json輸入（步驟03）::


[source, json]
----
{
  "name": "my_cluster"
}
----
處理類型:: 同步
輸出::
+
--
* 位置回應標頭中的叢集ID


--




[[step-4-configure-the-cluster]]
== 步驟 4：設定叢集

設定叢集時，您必須提供下列屬性。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 叢集 | 修補程式 | 叢集/｛cluster｝ 
|===
捲髮:: 請提供叢集 ID。


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step04 'https://10.21.191.150/api/clusters/CLUSTERID'
----
Json輸入（步驟04）::


[source, json]
----
{
  "dns_info": {
    "domains": ["lab1.company-demo.com"],
    "dns_ips": ["10.206.80.135", "10.206.80.136"]
    },
    "ontap_image_version": "9.5",
    "gateway": "10.206.80.1",
    "ip": "10.206.80.115",
    "netmask": "255.255.255.192",
    "ntp_servers": {"10.206.80.183"}
}
----
處理類型:: 同步
輸出:: 無




[[step-5-retrieve-the-node-name]]
== 步驟 5：擷取節點名稱

Deploy 管理公用程式會在建立叢集時自動產生節點識別碼和名稱。在設定節點之前，您需要擷取已指派的 ID。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 叢集 | 取得 | 叢集/｛cluster｝/節點 
|===
捲髮:: 請提供叢集 ID。


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/clusters/CLUSTERID/nodes?fields=id,name'
----
處理類型:: 同步
輸出::
+
--
* 陣列會記錄每個以唯一ID和名稱描述單一節點的資料


--




[[step-6-configure-the-nodes]]
== 步驟 6：設定節點

提供節點的基本組態，這是用於設定節點的三個 API 呼叫中的第一個。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 叢集 | 路徑 | 叢集/｛cluster｝/節點/｛node_id｝ 
|===
捲髮:: 請提供叢集 ID 和節點 ID。


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step06 'https://10.21.191.150/api/clusters/CLUSTERID/nodes/NODEID'
----
Json輸入（步驟06）:: 請提供 ONTAP Select 節點將執行的主機 ID。


[source, json]
----
{
  "host": {
    "id": "HOSTID"
    },
  "instance_type": "small",
  "ip": "10.206.80.101",
  "passthrough_disks": false
}
----
處理類型:: 同步
輸出:: 無




[[step-7-retrieve-the-node-networks]]
== 步驟 7：擷取節點網路

識別單節點叢集中節點所使用的資料與管理網路。單節點叢集不使用內部網路。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 叢集 | 取得 | 叢集/｛cluster｝/節點/｛node_id｝/網路 
|===
捲髮:: 請提供叢集 ID 和節點 ID。


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/ clusters/CLUSTERID/nodes/NODEID/networks?fields=id,purpose'
----
處理類型:: 同步
輸出::
+
--
* 兩筆記錄的陣列、每筆記錄分別說明節點的單一網路、包括唯一ID和用途


--




[[step-8-configure-the-node-networking]]
== 步驟 8：設定節點連網

設定資料網路和管理網路。單節點叢集不使用內部網路。


NOTE: 發出下列API呼叫兩次、每個網路一次。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 叢集 | 修補程式 | 叢集/｛cluster｝/節點/｛node_id｝/網路/｛network_id｝ 
|===
捲髮:: 請提供叢集 ID、節點 ID 和網路 ID。


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step08 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID/networks/NETWORKID'
----
Json輸入（步驟08）:: 請提供網路名稱。


[source, json]
----
{
  "name": "sDOT_Network"
}
----
處理類型:: 同步
輸出:: 無




[[step-9-configure-the-node-storage-pool]]
== 步驟 9：設定節點儲存資源池

設定節點的最後一步是附加儲存資源池。您可以透過vSphere Web用戶端或透過部署REST API（選用）來判斷可用的儲存資源池。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 叢集 | 修補程式 | 叢集/｛cluster｝/節點/｛node_id｝/網路/｛network_id｝ 
|===
捲髮:: 請提供叢集 ID、節點 ID 和網路 ID。


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step09 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID'
----
Json輸入（步驟09）:: 集區容量為2 TB。


[source, json]
----
{
  "pool_array": [
    {
      "name": "sDOT-01",
      "capacity": 2147483648000
    }
  ]
}
----
處理類型:: 同步
輸出:: 無




[[step-10-deploy-the-cluster]]
== 步驟 10：部署叢集

設定叢集和節點之後、即可部署叢集。

[cols="15,15,70"]
|===
| 類別 | HTTP動詞 | 路徑 


| 叢集 | 貼文 | 叢集/｛cluster｝/部署 
|===
捲髮:: 請提供叢集 ID。


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step10 'https://10.21.191.150/api/clusters/CLUSTERID/deploy'
----
Json輸入（步驟10）:: 請提供 ONTAP 系統管理員帳戶的密碼。


[source, json]
----
{
  "ontap_credentials": {
    "password": "mypassword"
  }
}
----
處理類型:: 非同步
輸出::
+
--
* 工作物件


--


.相關資訊
link:deploy-evaluation-ontap-select-ovf-template.html["部署 ONTAP Select 叢集的 90 天評估執行個體"]
