---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: 部署具有HA的雙節點叢集時、必須使用與其他叢集節點組態相同的規劃與組態。不過、在建立雙節點叢集時、您應該注意幾個差異。 
---
= 使用HA的雙節點叢集ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
部署具有HA的雙節點叢集時、必須使用與其他叢集節點組態相同的規劃與組態。不過、在建立雙節點叢集時、您應該注意幾個差異。

.目標環境
雙節點叢集由一組HA配對組成、專為遠端辦公室和分公司部署所設計。


NOTE: 雖然主要是針對遠端和分公司環境所設計、但您也可以視需要在資料中心內部署雙節點叢集。

.授權
您可以使用任何VMware vSphere授權來部署雙節點叢集。不過、VMware ROBO標準與進階授權是遠端與分公司部署的理想選擇。

.中介服務
當叢集由兩個節點組成時、當節點故障或失去通訊時、就無法達到所需的仲裁量。為了解決這些類型的腦分割情況、ONTAP Select 每個執行個體的示例都包含一個中介服務。此服務會連線至作用中雙節點叢集中的每個節點、以監控HA配對並協助管理故障。中介服務會在每個雙節點叢集相關的專用iSCSI目標上維護HA狀態資訊。


CAUTION: 如果您有一個或多個活動的雙節點集群，則管理這些集群的ONTAP Select Deploy 虛擬機器必須始終處於運作狀態。如果ONTAP Select Deploy 虛擬機器停止運作或發生故障，則中介服務不可用，且雙節點叢集的 HA 功能將會遺失。

.叢集和中介服務的位置
由於雙節點叢集通常部署在遠端或分支機構，因此它們可能遠離企業資料中心和提供管理支援的ONTAP Select Deploy 實用程式。透過這種配置， ONTAP Select Deploy 實用程式和叢集之間的管理流量將透過 WAN 傳輸。有關限制和約束的更多信息，請參閱發行說明。

. 為ONTAP Select Deploy 分配靜態 IP 位址


您必須為ONTAP Select Deploy 管理公用程式指派靜態 IP 位址。此要求適用於管理一個或多個ONTAP Select雙節點叢集的所有ONTAP Select Deploy 實例。
