---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: 在規劃安裝ONTAP Select 此功能時、您應該考慮幾項一般需求。 
---
= 部署一般需求與規劃ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在規劃安裝ONTAP Select 此功能時、您應該考慮幾項一般需求。



== 將部署公用程式與ONTAP Select 整個叢集配對

您可以在將部署公用程式的執行個體與ONTAP Select 叢集配對時、使用多種選項。


NOTE: 在所有部署案例中、只ONTAP Select 有一個部署管理公用程式執行個體可以管理單一的叢集和叢集中的節點。叢集無法由部署公用程式的兩個或多個不同執行個體來管理。



===== 每ONTAP Select 個叢集的公用程式執行個體

您可以ONTAP Select 使用部署公用程式的專屬執行個體來部署和管理每個叢集。有了這種一對一組態、每個公用程式對叢集配對之間都有明確的區隔。此組態可提供較小故障網域的高層級隔離。



===== 一個公用程式執行個體可用於多ONTAP Select 個實體叢集

您可以ONTAP Select 使用單一部署公用程式執行個體、在組織中部署及管理多個支援叢集。有了這種一對多組態、所有的處理和組態資料都是由部署公用程式的同一個執行個體來管理。


NOTE: 部署公用程式的一個執行個體最多可管理400 ONTAP Select 個節點或100個叢集。



== 使用認證儲存區進行驗證

這個包含帳戶資訊的ONTAP Select 資料庫儲存區是指利用此儲存區。部署會使用帳戶認證來執行主機驗證、做為叢集建立與管理的一部分。您應該瞭解認證儲存區如何在規劃ONTAP Select 還原部署時使用。


NOTE: 帳戶資訊會使用AES加密演算法和SHA-256雜湊演算法、安全地儲存在資料庫中。



===== 認證類型

支援下列類型的認證：

* 用於驗證Hypervisor主機的主機、做為將ONTAP Select VMware ESXi節點直接部署至VMware ESXi的一部分
* vCenter用於驗證vCenter伺ONTAP Select 服器、以在VMware vCenter管理主機時、將VMware節點部署至ESXi




===== 存取

認證存放區是在內部存取、做為使用部署執行一般管理工作的一部分、例如新增Hypervisor主機。您也可以透過部署Web使用者介面和CLI直接管理認證存放區。
