---
sidebar: sidebar 
permalink: reference_plan_dep_vmware.html 
keywords: plan, planning, ontap select deploy, vmware requirements 
summary: 在ONTAP Select VMware環境中安裝「VMware部署」公用程式之前、您應該先考量VMware環境的幾項特定需求與限制。 
---
= ONTAP Select 部署 Hypervisor 主機考量事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
有幾個與Hypervisor主機相關的規劃問題、您應該考慮。


CAUTION: 除非NetApp支援部門指示、否則您不應直接修改ONTAP Select 某個物件虛擬機器的組態。只能透過部署管理公用程式來設定及修改虛擬機器。若在ONTAP Select 部署公用程式之外變更不需NetApp支援人員協助的情況下、可能會導致虛擬機器故障、使其無法使用。



== Hypervisor不受限制

ONTAP Select 和 ONTAP Select Deploy 管理公用程式均獨立於 Hypervisor 。

ONTAP Select 和 ONTAP Select 部署管理均支援下列 Hypervisor ：

* VMware ESXi
* 核心型虛擬機器（KVM）



NOTE: 有關支援平台的其他詳細資訊，請參閱特定虛擬機器管理程序的規劃資訊和 link:reference_release_notes.html["發行說明"]。

.Hypervisor、適用於ONTAP Select 節點與管理公用程式
部署管理公用程式和 ONTAP Select 節點都會以虛擬機器的形式執行。您選擇部署公用程式的Hypervisor與ONTAP Select 您選擇的適用於各個節點的Hypervisor無關。您可以在配對兩種產品時、享有完全的靈活度：

* 在 VMware ESXi 上執行的 Deploy 公用程式可以建立和管理 VMware ESXi 或 KVM 上的 ONTAP Select 叢集。
* 在 KVM 上執行的 Deploy 公用程式可以在 VMware ESXi 或 KVM 上建立和管理 ONTAP Select 叢集。


.每個主機一個或多個ONTAP Select 節點的實例
每ONTAP Select 個支援節點都會以專屬虛擬機器的形式執行。您可以在相同的Hypervisor主機上建立多個節點、但有下列限制：

* 來自單ONTAP Select 一支援中心叢集的多個節點無法在同一部主機上執行。特定主機上的所有節點都必須來自不同ONTAP Select 的叢集。
* 您必須使用外部儲存設備。
* 如果您使用軟體RAID、則只能在ONTAP Select 主機上部署一個支援節點。


.叢集內節點的Hypervisor一致性
在一個叢集內的所有主機ONTAP Select 必須在Hypervisor軟體的相同版本和版本上執行。

.每個主機上的實體連接埠數目
您必須設定每個主機使用一個、兩個或四個實體連接埠。雖然您在設定網路連接埠時具有靈活度、但您應該盡可能遵循下列建議：

* 單節點叢集中的主機應該有兩個實體連接埠。
* 多節點叢集中的每個主機都應有四個實體連接埠


.將 ONTAP Select 與 ONTAP 硬體型叢集整合
您無法ONTAP Select 直接將某個節點新增至ONTAP 以硬體為基礎的叢集。不過、您可以選擇性地在ONTAP Select 一個叢集與一個硬體型ONTAP 的故障叢集之間建立叢集對等關係。



== VMware Hypervisor環境

在ONTAP Select VMware環境中安裝「VMware部署」公用程式之前、您應該先考量VMware環境的幾項特定需求與限制。

.ESXi主機伺服器硬體需求
您的 ESXi 虛擬機器管理程式主機必須符合若干最低資源需求。請檢查部署 ONTAP Select 的主機是否符合以下基本要求：

* ESXi伺服器：
+
** 硬體與軟體必須為64位元
** 必須遵循ONTAP Select 針對某個節點所定義的相同支援版本


* 虛擬CPU（2個）
* 虛擬記憶體（4 GB）
* 儲存設備（40 GB）
* 已啟用DHCP（也可以指派靜態IP位址）


.網路連線能力
請檢查 ONTAP Select Deploy 虛擬機器網路介面是否已配置，並具有單一管理 IP 位址。您可以使用 DHCP 動態指派 IP 位址，也可以手動設定靜態 IP 位址。

根據您的部署決策、部署VM必須能夠連線至vCenter伺服器、ESXi Hypervisor主機及ONTAP Select 其管理的各個節點。您必須設定防火牆以允許所需的流量。

Deploy 使用 VMware VIX API 與 vCenter 伺服器和 ESXi 主機通訊。首先，它使用基於 SSL 的 SOAP 協定在 TCP 連接埠 443 上建立連線。之後，它會在連接埠 902 上使用 SSL 協定開啟連線。此外，Deploy 也會發出 PING 指令來驗證您指定的 IP 位址上是否存在 ESXi 主機。

此外，Deploy 必須能夠使用以下協定與 ONTAP Select 節點和叢集管理 IP 位址進行通訊：

* Ping命令（ICMP）
* SSH（連接埠22）
* SSL（連接埠443）


.支援IP版本4
僅支援IP第4版（IPV4）ONTAP Select 。不支援IP版本6（IPv6）。此限制會以ONTAP Select 下列方式影響到流通：

* 您必須為部署虛擬機器的管理LIF指派一個IPV4位址。
* 「部署」無法建立ONTAP Select 設定為在ONTAP 整個過程中使用IPv6的動態節點。




== VMware vCenter 伺服器注意事項

.ESA 的 VMware vSphere 權限
要在 vCenter 中建立和管理 vSAN Express Storage Architecture (ESA)，您需要以下 vSphere 內容庫權限：


NOTE: 要存取內容庫權限，管理員需要授予您在 vCenter Server 中存取全域權限的權限。

* 新增庫項目
* 建立本地庫
* 刪除庫項目
* 刪除本機庫
* 下載文件
* 讀取儲存
* 更新文件
* 更新庫
* 更新庫項目
* 更新本地庫
* 查看配置設定

