---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: 您應該考量幾項與VMware環境相關的硬體需求與規劃問題。 
---
= ONTAP Select VMware Hypervisor 與硬體考量
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該考量幾項與VMware環境相關的硬體需求與規劃問題。



== Hypervisor需求

有幾項需求與ONTAP Select 執行效能不均的Hypervisor有關。


NOTE: 你應該複習一下link:reference_release_notes.html["發行說明ONTAP Select"]任何其他已知的限製或約束。



=== VMware授權

若要部署ONTAP Select 一個VMware叢集、貴組織必須擁有有效的VMware vSphere授權、以供執行ONTAP Select VMware的Hypervisor主機使用。您應該使用適合部署的授權。



=== 軟體相容性

您可以在 KVM 和 ESXi 虛擬機器管理程式上部署ONTAP Select 。

[role="tabbed-block"]
====
.KVM
--
ONTAP Select支援以下 KVM 虛擬機器管理程式版本：

* Red Hat Enterprise Linux (RHEL) 10.1、10.0、9.7、9.6、9.5、9.4、9.2、9.1、9.0、8.8、8.7 和 8.6 上的 KVM
* KVM 可在 Rocky Linux 10.0、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7 和 8.6 版本上運行


[NOTE]
====
在 RHEL 10.1 和 10.0 以及 Rocky Linux 10.0 主機上，KVM 虛擬機器管理程式的軟體 RAID 工作流程有一些限制。如需詳細資訊，請參閱下列知識庫文章：

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020： ONTAP Select Deploy：使用 RHEL 10 和 ROCKY 10 建立叢集 HWR 時出現警告訊息"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025： ONTAP Select DeployGUI：在執行 RHEL10/Rocky 10 的主機上，叢集建立頁面中 SWR 的儲存池和儲存磁碟不可見"^]


====
--
.ESXi
--
ONTAP Select支援以下 ESXi 虛擬機器管理程式版本：

* VMware ESXi 9.0
* VMware ESXi 8.0 U3
* VMware ESXi 8.0 U2
* VMware ESXi 8.0 U1 （內部版本 21495797 ）
* VMware ESXi 8.0 GA （組建 20513097 ）



NOTE: 只ONTAP Select 要VMware也持續支援相同版本、NetApp就能在識別的ESXi版本上提供支援。


NOTE: ESXi 7.0 GA 已停止提供服務。如果您有使用此版本的ONTAP Select集群，則必須按照以下說明昇級到受支援的版本： https://mysupport.netapp.com/matrix["互通性對照表工具IMT （不含）"^] 。

--
====


=== VMware vCenter和獨立式ESXi主機

如果ESXi Hypervisor主機是由vCenter伺服器管理、您必須使用vCenter認證將主機登錄至部署管理公用程式。您無法使用ESXi認證將主機登錄為獨立主機。



== 核心硬體需求

您部署ONTAP Select 的實體Hypervisor主機必須符合多項硬體需求。只要符合最低硬體需求、您就可以選擇Hypervisor主機的任何平台。下列廠商提供支援的硬體平台：Cisco、Dell、HP、Fujitsu、Lenovo、 和Supermmicro.


NOTE: 從ONTAP Select 9.9.1 開始，僅支援基於 Intel Xeon Sandy Bridge 或更高版本的 CPU 型號。

如需詳細資訊，請參閱 https://mysupport.netapp.com/matrix["互通性對照表工具， window=_blank"]。



=== 基本硬體需求

無論節點執行個體類型或授權項目為何、所有平台都有幾項常見的硬體需求。

.處理器
支援的微處理器包括用於伺服器的 Intel Xeon 處理器，請參閱link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Intel Xeon處理器、window=_blank"]了解更多。


NOTE: ONTAP Select 不支援進階 Micro 裝置（ AMD ）處理器。

.乙太網路組態
根據叢集大小、有多種支援的乙太網路組態。

[cols="2,3,3"]
|===
| 叢集大小 | 最低要求 | 建議要求 


| 單節點叢集 | 2 x 1GbE | 2個10GbE 


| 雙節點叢集或MetroCluster 不含任何功能的SDS | 4 x 1GbE或1 x 10GbE | 2個10GbE 


| 四節點、六節點、八節點、十節點或十二節點集群 | 2個10GbE | 4個10GbE或2個25/40GbE 
|===


=== 根據執行個體類型的其他硬體需求

根據節點執行個體類型、有多項額外的硬體需求。

請參閱 link:concept_lic_platforms.html["瞭解平台授權方案"] 以取得更多資訊。

[cols="a1,a2,a2,a2"]
|===
| 節點大小 | CPU 核心 | 記憶 | 所需的平台許可證產品 


| 小 | 六個或更多物理核心，其中四個保留用於ONTAP Select | 24 GB 或更大，其中 16 GB 保留給ONTAP Select | 標準型、高級型或高級 XL 型 


| 中 | 十個或更多物理核心，其中八個保留用於ONTAP Select | 72GB 或更大，其中 64GB 保留給ONTAP Select | Premium 或 Premium XL 


| 大 | 十八個或更多物理核心，其中十六個保留用於ONTAP Select | 136GB 或更大，其中 128GB 保留給ONTAP Select | 優質XL 
|===

NOTE: 根據平台授權、還有額外的磁碟需求。請參閱 link:reference_plan_ots_storage.html["儲存與RAID"] 以取得更多資訊。
