---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: 目前版本包含 ONTAP Select 的幾項新功能或改良功能。 
---
= ONTAP Select 的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解 ONTAP Select 支援版本的新功能和增強功能。



== ONTAP Select 9.17.1

ONTAP Select 9.17.1 包含多項新功能和改進。

KVM 主機上本機連接的 NVMe 磁碟的軟體 RAID 支持:: ONTAP Select 9.17.1 引進了對基於核心的虛擬機器 (KVM) 虛擬機器管理程式主機上ONTAP Select本機連接的 NVMe 磁碟的軟體 RAID 支援。
+
--
若要對本機連線的 NVMe 磁碟使用軟體 RAID，您需要link:kvm-host-configuration-and-preparation-checklist.html["配置 PCI 直通（DirectPath IO）"]當您準備 KVM 主機。這為 KVM 主機提供了對本地連接的 NVMe 磁碟的直接訪問，這是以下任務所必需的：

* 配置 KVM 主機以使用 NVMe 驅動器
* 部署叢集後使用軟體 RAID


link:concept_stor_swraid_local.html["了解本地連接儲存的軟體 RAID 設定服務"] 。

--
支援KVM主機叢集擴容與縮容:: 從ONTAP Select 9.17.1 開始，基於核心的虛擬機器 (KVM) 和 ESXi 虛擬機器管理程式主機均支援叢集擴充和收縮功能。對於ONTAP Select 9.16.1 和 9.15.1，僅 ESXi 虛擬機器管理程式主機支援叢集擴充和收縮功能。
+
--
您可以使用現有ONTAP Select叢集上的叢集擴展和收縮功能將叢集規模從六節點增加到八節點，或將叢集規模從八節點減少到六節點。

link:task_cluster_expansion_contraction.html["了解叢集擴充和收縮以及支援的 KVM 和 ESXi 虛擬機器管理程式版本"] 。

--
增強對 ESXi 主機上的叢集擴展和收縮的支持:: 從ONTAP Select 9.17.1 開始，ESXi 主機上的六節點叢集和十二節點叢集之間支援叢集擴展和收縮：
+
--
--
您可以按以下增量增加現有 ESXi 群集的群集大小：

* 從六個節點到八個、十個或十二個節點
* 從八個節點到十個或十二個節點
* 從十到十二個節點


您可以按以下增量減少現有 ESXi 群集的群集大小：

* 從十二個節點到十個、八個或六個節點
* 從十個節點到八個或六個節點
* 從八個節點到六個節點


--
link:task_cluster_expansion_contraction.html["了解叢集擴充和收縮以及支援的 KVM 和 ESXi 虛擬機器管理程式版本"] 。

--
支援SnapMirror雲:: 從ONTAP Select 9.17.1 開始， ONTAP Select支援SnapMirror雲端。 SnapMirrorSnapMirror是獲得許可的ONTAP功能，在部署ONTAP Select 9.17.1 叢集或將現有ONTAP Select叢集升級到 9.17.1 版本時預設啟用。
+
--
https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["了解SnapMirror雲端備份到物件存儲"^] 。

--
支援SnapLock Select Enterprise:: 從ONTAP Select 9.17.1 開始，新部署將自動獲得SnapLock Select Enterprise（包括防篡改快照鎖定）許可。對於從ONTAP Select 9.16.1 及更早版本升級，您需要SnapLocklink:https://mysupport.netapp.com/site/["NetApp 支援網站"^]並手動應用它。
在多節點叢集上支援 vSAN ESA:: 從ONTAP Select 9.17.1 開始，對 vSAN Express 儲存架構 (ESA) 的支援擴展，以部署多節點叢集。此增強功能可讓您部署 vSAN ESA 配置。
+
--
vSAN ESA 是一種 ESX 特定配置，是 vSphere 8 中引入的 VMware vSAN 的新架構。 vSAN ESA 旨在提供增強的效率、可擴展性和效能，尤其是在使用基於 NVMe 的 TLC 快閃記憶體裝置時。

ONTAP Select Deploy 和ONTAP Select for ESX 支援配置ONTAP Select單節點和多節點集群，使用 vSAN 或外部陣列類型的資料儲存作為其儲存池。

[NOTE]
====
要執行內容庫操作，您需要存取額外的權限等級。如果您使用受限角色，這對於 vSAN ESA 部署是必要的。

link:https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html["了解內容庫操作的存取權限級別"^] 。

====
--
更新了 NDA 驅動程式支援:: 從ONTAP Select 9.17.1 開始，FreeBSD NDA（NVMe 直接存取）裝置驅動程式取代了 NVD（NVMe 快速磁碟驅動程式）。 FreeBSD驅動程式透過實作 NVMe 命令協定來支援直接存取裝置。當您部署ONTAP Select 9.17.1 叢集或將現有ONTAP Select叢集升級至 9.17.1 版本時，設定 NVMe 裝置時會預設啟動 FreeBSD 驅動程式。
+
--
對於ONTAP Select 9.16.1 及更早版本，NVD 將繼續為ONTAP Select部署中的 NVMe 設備提供支援。

--
已更新 KVM Hypervisor 支援:: 從ONTAP Select 9.17.1 開始，Red Hat Enterprise Linux (RHEL) 9.6 和 Rocky Linux 9.6 支援 KVM 虛擬機器管理程式。




== ONTAP Select 9.16.1

ONTAP Select 9.16.1 包含多項新功能與改良功能。

更新的 NetApp 授權檔案支援:: 從 ONTAP Select 9.16.1 開始， NetApp 授權檔案（ NLF ）支援已更新。新的 NLF 格式包含 ARP ， ONTAP S3 和 S3 SnapMirror 功能的授權。link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["深入瞭解"]。
+
--
對於新的 ONTAP Select 9.16.1 部署，會自動套用新的 NLF 格式。當您將現有的 ONTAP Select 部署升級至 9.16.1 時，不會套用新的 NLF 格式。若要取得 ARP ， ONTAP S3 和 S3 SnapMirror 功能授權，您必須在升級後下載更新的 NLF 。如果您還原至 ONTAP Select 9.15.1 或更早版本，則必須重新安裝升級前所擁有的功能授權。

--
支援自主勒索軟體保護:: ONTAP Select 9.16.1 引進對自主勒索軟體保護（ ARP ）的支援。ONTAP Select 9.16.1 僅支援手動 ARP 更新，不支援自動更新。ONTAP Select 9.16.1 的 NLF 中包含 ARP 功能授權。link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["深入瞭解"]。
增強VMware ESXi支援:: ONTAP Select 9.16.1 支援 VMware ESXi 8.0 U3 。
已更新 KVM Hypervisor 支援:: 從ONTAP Select 9.16.1 開始，RHEL 9.5 和 Rocky Linux 9.5 支援 KVM 虛擬機器管理程式。




== ONTAP Select 9.15.1.1

ONTAP Select 9.15.1 包含多項新功能與改良功能。

已更新 KVM Hypervisor 支援:: 從 ONTAP Select 9.15.1 開始， RHEL 9.4 和 Rocky Linux 9.4 支援核心型虛擬機器（ KVM ） Hypervisor 。
支援叢集擴充和縮減:: 從 ONTAP Select 9.15.1 開始、支援叢集擴充和收縮。
+
--
* 從六節點叢集擴充至八節點叢集
+
您可以將叢集大小從六節點叢集增加至具有叢集擴充功能的八節點叢集。目前不支援從一個、兩個或四個節點叢集擴充至六個或八個節點叢集的叢集。link:task_cluster_expansion_contraction.html#expand-the-cluster["深入瞭解"]。

* 叢集將八個節點縮減為六個節點叢集
+
您可以使用叢集縮減功能、將叢集大小從八節點叢集減少為六節點叢集。目前不支援從六個或八個節點叢集到一個、兩個或四個節點叢集的叢集收縮。link:task_cluster_expansion_contraction.html#contract-the-cluster["深入瞭解"]。



--



NOTE: 叢集擴充和收縮支援僅限於 ESX 叢集。



== ONTAP Select 9.14.1.

ONTAP Select 9.14.1 包含多項新功能與改良功能。

支援 KVM Hypervisor:: 從 ONTAP Select 9.14.1 開始、 KVM Hypervisor 的支援已恢復。以前、 ONTAP Select 9.10.1 中移除在 KVM Hypervisor 上部署新叢集的支援、並在 ONTAP Select 9.11.1 中移除對管理現有 KVM 叢集和主機的支援、但不包括離線或刪除。
不再支援部署 VMware vCenter 外掛程式:: 從 ONTAP Select 9.14.1 開始、不再支援部署 VMware vCenter 外掛程式。
更新的 ONTAP Select 部署支援:: 如果您執行的 ONTAP Select 版本低於 9.14.1P2 、則應儘快升級至 ONTAP Select Deploy 9.14.1P2 。如需詳細資訊、請參閱 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1 版本資訊"^]。
增強VMware ESXi支援:: ONTAP Select 9.14.1 支援 VMware ESXi 8.0 U2 。




== ONTAP Select 9.13.1%

ONTAP Select 9.13.1 包含多項新功能與改良功能。

支援 NVMe over TCP:: 升級至 ONTAP Select 9.13.1 時、您必須擁有新的授權、才能透過 TCP 支援 NVMe 。當您第一次從 9.13.1 版開始部署 ONTAP Select 時、就會自動包含此授權。
更新VMware ESXi支援:: 從 ONTAP 9 。 13.1 開始、硬體版本 4 及更新版本支援 VMware ESXi 8.0.1 GA （組建 20513097 ）。
更新的 ONTAP Select 部署支援:: 截至 2024 年 4 月、 ONTAP Select Deploy 9.13.1 已不再適用於 NetApp 支援網站 。如果您執行的是 ONTAP Select Deploy 9.13.1 、則應儘快升級至 ONTAP Select Deploy 9.14.1P2 。如需詳細資訊、請參閱 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1 版本資訊"^]。




== 零點9.12.1. ONTAP Select

目前發行的核心版的核心版大部分新開發成果、均可讓您受益於此功能ONTAP ONTAP Select 。不包含ONTAP Select 任何特定於功能更新或改進功能。

自 2024 年 4 月起、 ONTAP Select Deploy 9.12.1 不再適用於 NetApp 支援網站 。如果您執行的是 ONTAP Select Deploy 9.12.1 、則應儘快升級至 ONTAP Select Deploy 9.14.1P2 。如需詳細資訊、請參閱 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1 版本資訊"^]。



== 零點9.11.1. ONTAP Select

包含多項新功能與改良功能ONTAP Select 。

增強VMware ESXi支援:: 支援VMware ESXi 7.0 U3C的VMware ESXi 9.11.1。ONTAP Select
支援VMware NSxT-T:: VMware NSS-T 3.1.2版已符合VMware NSS-9.10.1及更新版本的資格ONTAP Select 。將NSS-T搭配ONTAP Select 部署有OVA檔案和ONTAP Select 支援此功能的整合式管理公用程式的單節點叢集使用時、沒有任何功能問題或不足之處。不過、將NSS-T搭配ONTAP Select 使用於不支援任何功能的多節點叢集時、您應該注意ONTAP Select 下列有關《The S59.11.1》的限制：
+
--
* 網路連線檢查工具
+
在NSX T型網路上執行時、透過部署CLI提供的網路連線檢查程式會失敗。



--
不再支援KVM Hypervisor::
+
--
* 從功能更新至功能更新至功能更新、您將無法再在KVM Hypervisor上部署新叢集ONTAP Select 。
* 從功能支援的版本起、除了「離線」和「刪除」功能之外、所有的管理功能都不再適用於現有的KVM叢集和主機ONTAP Select 。
+
NetApp強烈建議客戶規劃並執行完整的資料移轉、從ONTAP Select 適用於KVM的VMware移轉至ONTAP 任何其他的支援平台、包括ONTAP Select 適用於ESXi的VMware。如需詳細資訊、請參閱 https://mysupport.netapp.com/info/communications/ECMLP2877451.html["EOA通知"^]



--




== 零點9.10.1 ONTAP Select

包含多項新功能與改良功能ONTAP Select 。

支援VMware NSxT-T:: 符合VMware NSS-T 3.1.2版資格的S209.10.1。ONTAP Select將NSS-T搭配ONTAP Select 部署有OVA檔案和ONTAP Select 支援此功能的整合式管理公用程式的單節點叢集使用時、沒有任何功能問題或不足之處。不過、將NSxT-T搭配ONTAP Select 使用支援不支援的多節點叢集時、您應該注意下列需求和限制：
+
--
* 叢集MTU
+
您必須手動將叢集MTU大小調整為8800、才能部署叢集以因應額外的負荷。VMware指南是在使用NSX T時允許使用200位元組的緩衝區

* 網路4x10Gb組態
+
針對配置有四個NIC的VMware ESXi主機上的VMware ESXi部署、部署公用程式會提示您遵循最佳實務做法、在兩個不同的連接埠群組之間分割內部流量、以及在兩個不同的連接埠群組之間分割外部流量。ONTAP Select不過、使用重疊網路時、此組態無法運作、您應該忽略建議。在這種情況下、您應該只使用一個內部連接埠群組和一個外部連接埠群組。

* 網路連線檢查工具
+
在NSX T型網路上執行時、透過部署CLI提供的網路連線檢查程式會失敗。



--
不再支援KVM Hypervisor:: 從功能更新至功能更新至功能更新、您將無法再在KVM Hypervisor上部署新叢集。ONTAP Select不過、如果您將叢集從舊版升級至9.10.1、您仍可使用部署公用程式來管理叢集。




== 部分9.9.1 ONTAP Select

包含多項新功能與改良功能ONTAP Select 。

處理器系列支援:: 從 ONTAP Select 9.9.1 開始、 ONTAP Select 僅支援來自 Intel Xeon Sandy Bridge 或更新版本的 CPU 機型。
更新VMware ESXi支援:: 支援VMware ESXi的ONTAP Select 功能已透過VMware 9.9.1增強。現在支援下列版本：
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1.


--




== 部分9.8 ONTAP Select

在更新功能ONTAP Select 方面、有幾項功能已在更新。

高速介面:: 高速介面功能可同時提供25G（25GbE）和40G（40GbE）選項、以增強網路連線能力。若要在使用這些較高速度時達到最佳效能、您應遵循ONTAP Select 《The》（《The》）文件中所述的連接埠對應組態最佳實務做法。
更新VMware ESXi支援:: 關於支援VMware ESXi的ONTAP Select 問題、共有兩項關於支援VMware ESXi的變更。
+
--
* 支援ESXi 7.0（GA build 15843807及更新版本）
* 不再支援ESXi 6.0


--

