---
sidebar: sidebar 
permalink: sizing-capacity-tier-license.html 
keywords: license, licensing, Capacity Tiers, usable, space 
summary: Capacity Tiers 授權是基於每個節點管理的底層磁碟容量，而非節點、HA-pair 或叢集的可用容量。每個 Capacity Tiers 授權都分配給一個特定容量的個別節點序號，且需要隨附的支援合約。 
---
= ONTAP Select Capacity Tiers 授權容量規劃注意事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量層級授權是基於每個 ONTAP Select 節點所管理的底層磁碟容量，而非節點、HA 配對或叢集的可用容量。每個容量層級授權都分配給一個特定的節點序號，並對應一個指定的容量，且需要簽訂相應的支援合約。

容量層級授權的授權容量以 TB 為單位，最小值為 1 TB。授權容量的計算方法是將可用空間乘以例行成本係數。例行成本係數用於估算 ONTAP Select 軟體例行成本容量，該容量將從可用空間中扣除，並用於確定 NVMe、SSD、HDD 或虛擬磁碟機的 ONTAP Select 容量。單節點叢集和多節點（基於 HA 配對）叢集的例行成本係數有所不同：

* 單節點叢集的開銷係數為 1.13
* 多節點叢集的開銷係數為 2.67


您需要根據可用空間計算授權容量，以確保有足夠的容量來滿足您的部署。例如，您需要一個 HA 配對具備 10 TB 的可用容量（每個節點 5 TB）：

* 對於 HA 配對，資料會在兩個節點之間進行複製以實現備援，因此，對於 HA 配對中的 10 TB 可用容量，每個節點需要 10 TB 的空間，以防其中一個節點離線。
* 係數 2.67 使每個節點的容量翻倍，並增加了 ONTAP Select 運作所需的例行成本容量（0.67）。
* 每個節點的授權容量為 14 TB（5 x 2.67 = 13.35）。對於 HA 配對，您需要兩個 14 TB 的授權才能擁有 10 TB 的可用容量。


[cols="25,30,45"]
|===
| 說明 | 單節點 | HA配對 


| 可用空間 | 10 TB | 每個節點 5 TB HA 配對 10 TB 


| 授權空間 | 12 TB（10 x 1.13 = 11.3，向上取整到下一個整數 TB） | 兩個 14 TB 授權（5 x 2.67 = 13.35，向上取整到下一個完整 TB） 


| 每個節點的最大可用空間 *註*：每個節點或 HA 配對的最大管理空間為 400 TB | 353 TB（400 / 1.13）  a| 
HA 配對的每個節點：

* 149 TB（400 / 2.67）


在多節點叢集中，每個 HA 對：

* 雙節點：298 TB（2 x 149）
* 四節點：596 TB（4 x 149）
* 六節點：894 TB（6 x 149）
* 八節點：1,192 TB（8 x 149）
* 十節點：1,490 TB（10 x 149）
* 十二節點：1,788 TB（12 x 149）


|===
.接下來
link:task_lic_acquire_ct.html["取得 ONTAP Select 的容量層授權"]
