---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 您可以使用命令列介面、就地升級現有的部署公用程式虛擬機器。 
---
= 升級 ONTAP Select 部署執行個體
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 ONTAP Select Deploy 實用程式 CLI 就地升級現有的 ONTAP Select Deploy 實用程式虛擬機器。

您可以從 ONTAP Select Deploy 9.17.1 或 9.16.1 直接升級到 ONTAP Select Deploy 9.18.1。要從更早的版本（例如 ONTAP Select Deploy 9.15.1）升級，您必須先升級到 ONTAP Select Deploy 9.16.1 或 9.17.1，然後再升級到 ONTAP Select Deploy 9.18.1。

[NOTE]
====
如果您安裝的是舊版的 ONTAP Select Deploy 管理公用程序，則應升級至最新版本。ONTAP Select 節點和 ONTAP Select Deploy 元件是獨立升級的。如需更多詳細資訊，請參閱 link:concept_adm_upgrading_nodes.html["升級 ONTAP Select 節點"^]。

====
.開始之前
確認在升級過程中 ONTAP Select Deploy 未用於執行任何其他任務。



== 步驟 1：下載升級套件

若要開始升級過程，請從 NetApp 支援網站下載 ONTAP Select Deploy 升級檔案。升級套件以單一壓縮檔案的形式提供。

.步驟
. 存取 link:https://mysupport.netapp.com/site/downloads/["NetApp 支援網站下載"^] 頁面。
. 向下捲動並選擇 *ONTAP Select Deploy*。
. 選擇所需的 ONTAP Select 版本。
. 檢閱終端使用者授權合約（ EULA ）、然後選取 * 接受並繼續 * 。
. 選擇並下載適當的 *ONTAP Select Deploy Upgrade* 套件。視需要回應所有提示。




== 步驟 2：將軟體包上傳到ONTAP Select Deploy 虛擬機

下載軟體包後，您需要將檔案上傳到ONTAP Select Deploy 虛擬機器。

.關於這項工作
此任務介紹了一種將檔案上傳到ONTAP Select Deploy 虛擬機器的方法。可能還有其他選項更適合您的環境。

.開始之前
* 驗證升級檔案是否在本機工作站上可用。
* 驗證您是否擁有管理員使用者帳戶的密碼。


.步驟
. 在本地工作站的命令提示字元中，使用 `scp`使用（安全複製協定）實用程式將映像檔上傳到ONTAP Select Deploy 虛擬機，如下範例所示：
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
升級檔案儲存在管理使用者的主目錄中。



== 步驟3：應用升級包

將升級檔案上傳到ONTAP Select Deploy 虛擬機器後，即可套用升級。

.開始之前
* 驗證升級檔案在ONTAP Select Deploy 實用程式虛擬機器中放置的目錄。
* 驗證在執行升級時ONTAP Select Deploy 未用於執行任何其他任務。


.步驟
. 使用管理員帳戶透過 SSHSign inONTAP Select Deploy 實用程式 CLI。
. 使用適當的目錄路徑和檔案名稱執行升級：
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
範例命令：

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.完成後
在升級過程完成之前，系統會要求您建立ONTAP Select Deploy 虛擬機器配置的備份。此外，您應該清除瀏覽器快取，以便可以查看新建立的ONTAP Select Deploy 頁面。
