---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 您可以使用命令列介面、就地升級現有的部署公用程式虛擬機器。 
---
= 升級部署執行個體
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用命令列介面、就地升級現有的部署公用程式虛擬機器。



== 開始之前

確保在升級期間不會使用部署來執行任何其他工作。如需升級部署公用程式的相關資訊和限制、請參閱最新版本說明。



== 正在下載升級套件

若要開始升級程序、您必須從NetApp支援網站下載適當的部署虛擬機器升級檔案。升級套件會格式化為單一壓縮檔案。

.步驟
. 使用網頁瀏覽器存取NetApp支援網站、然後按一下*支援快速連結*。
. 按一下「*熱門工作*」下的「*下載軟體*」、然後登入。
. 按一下*尋找您的產品*。
. 向下捲動並按一下* ONTAP Select 「*」「部署升級*」。
. 選取所需的升級套件版本。
. 檢閱終端使用者授權合約（EULA）、然後按一下*「Accept & Continue（接受並繼續）」*。
. 選取並下載適當的套件、視環境需求回應所有提示。


.相關資訊
link:https://mysupport.netapp.com["NetApp支援"^]



== 將套件上傳至部署虛擬機器

取得升級套件之後、您必須將檔案上傳至部署虛擬機器。

.開始之前
您必須在本機工作站上提供升級檔案。您也必須擁有系統管理員使用者帳戶的密碼。

.關於此工作
此工作說明將檔案上傳至部署虛擬機器的一種方法。可能還有其他更適合您環境的選項。

.步驟
. 在本機工作站的命令Shell中、使用sftp公用程式將映像檔上傳至部署虛擬機器。
+
範例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put ONTAPdeploy2.12_upgrade.tar.gz
exit
....


.結果
升級檔案儲存在管理使用者的主目錄中。



== 套用升級套件

將升級檔案上傳至部署虛擬機器之後、即可套用升級。

.開始之前
您必須知道升級檔案位於Deploy公用程式虛擬機器的哪個目錄。此外、請確保在執行升級時、不會使用部署來執行任何其他工作。

.步驟
. 以系統管理員帳戶使用SSH登入部署公用程式CLI。
. 使用適當的目錄路徑和檔案名稱執行升級：
+
「部署升級-套件路徑檔案路徑」

+
範例

+
....
deploy upgrade -package-path /home/admin/
ONTAPdeploy2.12_upgrade.tar.gz
....


.完成後
升級程序完成後、系統會要求您建立部署虛擬機器組態的備份。您也應該清除瀏覽器快取、以便檢視新建立的部署頁面。
