---
sidebar: sidebar 
permalink: task_install_deploy.html 
keywords: install, installing, ontap select deploy, deploy administration utility, deploy utility 
summary: 您需要安裝ONTAP Select 「整合式」管理公用程式、並使用公用程式來建立ONTAP Select 一個「叢集」。 
---
= 安裝ONTAP Select 部署
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您需要安裝ONTAP Select 「整合式」管理公用程式、並使用公用程式來建立ONTAP Select 一個「叢集」。



== 步驟 1：下載虛擬機器鏡像

從NetApp支援網站下載ONTAP Select軟體包。

.開始之前
https://mysupport.netapp.com/site/user/registration["您擁有註冊的 NetApp 支援網站帳戶"^]。

.關於這項工作
ONTAP Select Deploy 管理公用程式是根據開放式虛擬化格式（ OVF ）標準、封裝為虛擬機器（ VM ）。單一壓縮檔案具有後置字元 `ova`。VM 提供 ONTAP Select 節點的部署伺服器和安裝映像。

.步驟
. 存取 link:https://mysupport.netapp.com/site/["NetApp 支援網站"^] 使用網頁瀏覽器登入。
. 從菜單中選擇 * 下載 * ，然後從下拉菜單中選擇 * 下載 * 。
. 在 [ 下載 ] 頁面上，選取 [ 所有產品 A-Z ] 底下的字母 *O* 。
. 向下捲動並選取 * ONTAP Select * 。
. 選取所需的套件版本。
. 檢閱終端使用者授權合約（ EULA ）、然後選取 * 接受並繼續 * 。
. 選取並下載適當的套件、視需要回應所有提示。




== 步驟 2：驗證ONTAP Select Deploy OVA 簽名

安裝安裝包之前，請先確認ONTAP Select開放虛擬化設備 (OVA) 簽章。

.開始之前
確認您的系統符合下列需求：

* 用於基本驗證的 Openssl 版本 1.0.2 至 3.0
* 線上憑證狀態傳輸協定（ OCSP ）驗證的公用網際網路存取


.步驟
. 從 NetApp 支援網站 的產品下載頁面取得下列檔案：
+
[cols="2*"]
|===
| 檔案 | 說明 


| `ONTAP-Select-Deploy-Production.pub` | 用於驗證簽名的公開金鑰。 


| `csc-prod-chain-ONTAP-Select-Deploy.pem` | 公共憑證授權單位（ CA ）信任鏈結。 


| `csc-prod-ONTAP-Select-Deploy.pem` | 用於產生金鑰的憑證。 


| `ONTAPdeploy.ova` | ONTAP Select 的產品安裝執行檔。 


| `ONTAPdeploy.ova.sig` | SHA-256 演算法會遭到雜湊、然後由遠端支援代理程式（ RSA ）使用簽署 `csc-prod` 安裝程式的金鑰和簽名。 
|===
. 確認 `ONTAPdeploy.ova.sig` 檔案正在使用相關的憑證和驗證命令。
. 使用下列命令驗證簽名：
+
[listing]
----
openssl dgst  -sha256 -verify ONTAP-Select-Deploy-Production.pub -signature ONTAPdeploy.ova.sig  ONTAPdeploy.ova
----




== 步驟 3：部署虛擬機

使用 OVF VM 映像安裝並啟動ONTAP Select Deploy VM。作為安裝過程的一部分，您需要設定網路介面以使用 DHCP 或靜態 IP 設定。

.開始之前
對於 ESXi Hypervisor 、您必須準備部署 ONTAP Select Deploy VM ：

* 安裝VMware Client整合外掛程式或視需要執行類似的組態、即可在瀏覽器中啟用OVF功能
* 如果您要動態指派 IP 位址給部署的虛擬機器、請在 VMware 環境中啟用 DHCP


對於 ESXi 和 KVM Hypervisor 、您必須擁有在建立 VM 時要使用的組態資訊、包括 VM 名稱、外部網路和主機名稱。定義靜態網路組態時、您需要下列額外資訊：

* 部署 VM 的 IP 位址
* 網路遮罩
* 閘道（路由器）的IP位址
* 主要DNS伺服器的IP位址
* 第二部DNS伺服器的IP位址
* DNS搜尋網域


.關於這項工作
如果您使用vSphere、則「部署OVF範本精靈」會提供表單、以提供所有部署組態資訊、包括網路組態。不過、如果您選擇不使用此表單、則可以改用部署 VM 的主控台來設定網路。

.步驟
您所遵循的步驟取決於您是使用 ESXi 還是 KVM Hypervisor 。

[role="tabbed-block"]
====
.ESXi
--
. 存取vSphere用戶端並登入。
. 瀏覽至階層中的適當位置、然後選取*部署OVF範本*。
. 選取OVA檔案並完成「部署OVF範本」精靈、選取適合您環境的選項。
+
您必須定義系統管理員帳戶的密碼。登入部署公用程式時、您必須提供此密碼。

. 部署虛擬機器之後，請選取新的虛擬機器。如果尚未根據您對部署精靈的輸入來開啟電源，請手動開啟電源。
. 如有需要、您可以使用 VM 主控台設定部署網路：
+
.. 按一下*主控台*索引標籤、即可存取ESXi主機設定Shell並監控開機程序。
.. 等待下列提示：
+
主機名稱：

.. 輸入主機名稱、然後按* Enter *。
.. 等待下列提示：
+
提供管理員使用者密碼：

.. 輸入密碼並按* Enter *。
.. 等待下列提示：
+
使用DHCP設定網路資訊？[n]：

.. 鍵入 *n* 可定義靜態 IP 組態，或鍵入 *y* 使用 DHCP ，然後選取 *Enter* 。
.. 如果您選擇靜態組態、請視需要提供所有網路組態資訊。




--
.KVM
--
. 在 Linux 伺服器登入 CLI ：
+
[listing]
----
ssh root@<ip_address>
----
. 建立新目錄並擷取原始 VM 映像：
+
[listing]
----
mkdir /home/select_deploy25
cd /home/select_deploy25
mv /root/<file_name> .
tar -xzvf <file_name>
----
. 建立並啟動執行 Deploy 管理公用程式的 KVM VM ：
+
[listing]
----
virt-install --name=select-deploy --vcpus=2 --ram=4096 --os-variant=debian10 --controller=scsi,model=virtio-scsi --disk path=/home/deploy/ONTAPdeploy.raw,device=disk,bus=scsi,format=raw --network "type=bridge,source=ontap-br,model=virtio,virtualport_type=openvswitch" --console=pty --import --noautoconsole
----
. 如有需要、您可以使用 VM 主控台設定部署網路：
+
.. 連線至 VM 主控台：
+
[listing]
----
virsh console <vm_name>
----
.. 等待下列提示：
+
[listing]
----
Host name :
----
.. 鍵入主機名稱並選擇 *Enter* 。
.. 等待下列提示：
+
[listing]
----
Use DHCP to set networking information? [n]:
----
.. 鍵入 *n* 可定義靜態 IP 組態，或鍵入 *y* 使用 DHCP ，然後選取 *Enter* 。
.. 如果您選擇靜態組態、請視需要提供所有網路組態資訊。




--
====


== 步驟 4：Sign inDeploy Web 介面

Sign inWeb 使用者介面以確認部署實用程式可用並執行初始配置。

.步驟
. 使用IP位址或網域名稱、將瀏覽器指向Deploy公用程式：
+
https://<ip_address>/`

. 提供系統管理員（admin）帳戶名稱和密碼並登入。
. 如果顯示 * 歡迎使用 ONTAP Select * 快顯視窗、請檢閱必要條件、然後選取 * 確定 * 繼續。
. 如果這是第一次登入，但您並未使用 vCenter 提供的精靈來安裝部署，請在出現提示時提供下列組態資訊：
+
** 系統管理員帳戶的新密碼（必填）
** 選擇性的AutoSupport
** 具有帳戶認證的vCenter伺服器（選用）




.相關資訊
* link:task_cli_signing_in.html["登入以使用 SSH 部署"]
* link:deploy-evaluation-ontap-select-ovf-template.html["部署 ONTAP Select 叢集的 90 天評估執行個體"]

