---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 您可以使用命令列介面、就地升級現有的部署公用程式虛擬機器。 
---
= 升級 ONTAP Select 部署執行個體
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用命令列介面、就地升級現有的部署公用程式虛擬機器。



== 開始之前

確保在升級期間不會使用部署來執行任何其他工作。如需升級部署公用程式的相關資訊和限制、請參閱最新版本說明。


NOTE: 如果您已安裝舊版 ONTAP Select Deploy 管理公用程式、則應升級至目前版本。ONTAP Select 節點和 ONTAP Select Deploy 元件會分別升級。請參閱 link:concept_adm_upgrading_nodes.html["升級 ONTAP Select 節點"^] 以取得更多詳細資料。



== 下載升級套件

若要開始升級程序、您必須從NetApp支援網站下載適當的部署虛擬機器升級檔案。升級套件會格式化為單一壓縮檔案。

.步驟
. 存取 link:https://mysupport.netapp.com/site/["NetApp 支援網站"^] 使用網頁瀏覽器、並從「下載」功能表中選擇 * 「下載 * 」。
. 向下捲動並選取 * ONTAP Select Deploy Upgrade* 。
. 選取所需的升級套件版本。
. 檢閱終端使用者授權合約（ EULA ）、然後選取 * 接受並繼續 * 。
. 選取並下載適當的套件、視環境需求回應所有提示。




== 將套件上傳至部署虛擬機器

取得升級套件之後、您必須將檔案上傳至部署虛擬機器。

.開始之前
您必須在本機工作站上提供升級檔案。您也必須擁有系統管理員使用者帳戶的密碼。

.關於此工作
此工作說明將檔案上傳至部署虛擬機器的一種方法。可能還有其他更適合您環境的選項。

.步驟
. 在本機工作站的命令 Shell 中、使用 scp 公用程式將影像檔案上傳至部署虛擬機器。
+
範例

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
升級檔案儲存在管理使用者的主目錄中。



== 套用升級套件

將升級檔案上傳至部署虛擬機器之後、即可套用升級。

.開始之前
您必須知道升級檔案位於Deploy公用程式虛擬機器的哪個目錄。此外、請確保在執行升級時、不會使用部署來執行任何其他工作。

.步驟
. 以系統管理員帳戶使用SSH登入部署公用程式CLI。
. 使用適當的目錄路徑和檔案名稱執行升級：
+
「部署升級-套件路徑檔案路徑」

+
範例

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.完成後
升級程序完成之前、系統會要求您建立部署虛擬機器組態的備份。此外、您也應該清除瀏覽器快取、以便檢視新建立的部署頁面。
