---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: 如果由於某種原因而導致無法使用此功能、您將無法管理節點和叢集。ONTAP Select ONTAP Select此外、所有雙節點叢集都會喪失HA功能、因為部署所包含的中介服務無法使用。如果發生不可恢復的故障、您必須恢復部署公用程式執行個體、才能還原管理和HA功能。 
---
= 恢復雙節點叢集的部署公用程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果由於某種原因而導致無法使用此功能、您將無法管理節點和叢集。ONTAP Select ONTAP Select此外、所有雙節點叢集都會喪失HA功能、因為部署所包含的中介服務無法使用。如果發生不可恢復的故障、您必須恢復部署公用程式執行個體、才能還原管理和HA功能。



== 開始之前

您應該先做好準備、再嘗試恢復部署公用程式的執行個體、以確保成功。

您應該熟悉幾個管理程序、並擁有必要的資訊。

您必須能夠在ONTAP Select Hypervisor環境中安裝新的更新版的更新版的更新版本。

您必須能夠登入ONTAP 到該叢集的CLI、ONTAP Select 並使用Shell介面。

您必須判斷是否有來自故障部署公用程式執行個體的組態資料備份、該執行個體包含ONTAP Select 了雙節點叢集。您的備份可能不包含叢集。

您應該能夠還原部署組態資料的備份、視所使用的還原程序而定。

您必須知道故障的原始部署公用程式虛擬機器的IP位址。

您必須判斷是否使用容量資源池或容量層授權。如果您使用容量集區授權、則必須在還原或還原部署執行個體之後、重新安裝每個容量集區授權。

您必須決定恢復ONTAP Select 某個執行個體時要使用的程序。您的決定取決於您是否備份來自原始故障部署公用程式的組態資料、該公用程式包含ONTAP Select 了雙節點叢集。

[cols="35,65"]
|===
| 您是否有包含雙節點叢集的部署備份？ | 恢復程序 


| 是的 | 使用組態備份還原部署公用程式執行個體 


| 否 | 重新設定及還原部署公用程式執行個體 
|===


== 使用組態備份還原部署公用程式執行個體

如果您有包含雙節點叢集的失敗部署公用程式執行個體備份、您可以將組態資料還原至新的部署虛擬機器執行個體。然後、您必須執行ONTAP Select 額外的組態來完成恢復、將兩個節點放在一個叢集內。

您必須備份原始故障部署虛擬機器的組態資料、其中包含雙節點叢集。您必須能夠登入ONTAP 雙節點叢集的CLI、並知道ONTAP 兩個節點的名稱。

由於還原的組態備份包含雙節點叢集、因此在新的部署公用程式虛擬機器中、會重新建立協調器iSCSI目標和信箱。

.步驟
. 準備ONTAP Select 一套全新的示例的示例：
+
.. 安裝新的部署公用程式虛擬機器。
.. 將部署組態從先前的備份還原至新的虛擬機器。
+
如需安裝與還原程序的詳細資訊、請參閱相關工作。



. 登入ONTAP 到位在現象雙節點叢集的指令行介面。ONTAP Select
. 進入進階權限模式：
+
《et adv'》

. 如果新部署虛擬機器的IP位址與原始部署虛擬機器不同、您必須移除舊的中介iSCSI目標並新增目標：
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
「<ip_address>'參數是新部署虛擬機器的IP位址。

+
這些命令可讓ONTAP Select 各個節點探索新部署公用程式虛擬機器上的信箱磁碟。

. 確定中介磁碟的名稱：
+
「磁碟顯示-容器型中介器」

. 將信箱磁碟指派給兩個節點：
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>
disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. 確認已啟用儲存容錯移轉：
+
「容錯移轉顯示」



如果您使用容量集區授權、則必須重新安裝每個容量集區授權。如需其他詳細資料、請參閱重新安裝容量資源池授權_。



== 重新設定及還原部署公用程式執行個體

如果您沒有包含雙節點叢集的失敗部署公用程式執行個體備份、則必須在新的部署虛擬機器中設定中介iSCSI目標和信箱。然後、您必須執行ONTAP Select 額外的組態來完成恢復、將兩個節點放在一個叢集內。

您必須擁有新部署公用程式執行個體的中介目標名稱。您必須能夠登入ONTAP 雙節點叢集的CLI、並知道ONTAP 兩個節點的名稱。

您可以選擇性地將組態備份還原至新的部署虛擬機器、即使該虛擬機器不包含雙節點叢集。由於雙節點叢集並非以還原方式重新建立、因此您必須透過ONTAP Select 部署的「支援資訊」線上文件網頁、將中介iSCSI目標和信箱手動新增至新的部署公用程式執行個體。您必須能夠登入雙節點叢集、並知道ONTAP 兩個節點的名稱。


NOTE: 恢復程序的目標是將雙節點叢集還原至正常狀態、以便執行正常的HA接管和恢復作業。

.步驟
. 準備ONTAP Select 一套全新的示例的示例：
+
.. 安裝新的部署公用程式虛擬機器。
.. （可選）將部署組態從先前的備份還原至新的虛擬機器。
+
如果還原先前的備份、新的部署執行個體將不會包含雙節點叢集。如需安裝與還原程序的詳細資訊、請參閱相關資訊一節。



. 登入ONTAP 到位在現象雙節點叢集的指令行介面。ONTAP Select
. 進入進階權限模式：
+
《et adv'》

. 取得中介iSCSI目標名稱：
+
「儲存iSCSI啟動器顯示-目標類型信箱」

. 存取新部署公用程式虛擬機器的線上文件網頁、然後使用admin帳戶登入：
+
http://<ip_address>/api/ui`

+
您必須使用部署虛擬機器的IP位址。

. 按一下*「媒體」*、然後按*「Get /Mediator*」。
. 按一下*試用！*以顯示由部署維護的協調器清單。
+
記下所需中介執行個體的ID。

. 按一下*「媒體」*、然後按*「POST」*。
. 請提供「中介人ID的值。
. 按一下「iSCSI目標」旁邊的*模型*、然後填寫名稱值。
+
使用iqn_name參數的目標名稱。

. 按一下*「試試看！*」以建立協調器iSCSI目標。
+
如果申請成功、您將會收到HTTP狀態代碼200。

. 如果新部署虛擬機器的IP位址與原始部署虛擬機器不同、您必須使用ONTAP CLI移除舊的中介iSCSI目標、並新增新目標：
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
「<ip_address>'參數是新部署虛擬機器的IP位址。



這些命令可讓ONTAP Select 各個節點探索新部署公用程式虛擬機器上的信箱磁碟。

. 確定中介磁碟的名稱：
+
「磁碟顯示-容器型中介器」

. 將信箱磁碟指派給兩個節點：
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. 確認已啟用儲存容錯移轉：
+
「容錯移轉顯示」



如果您使用容量集區授權、則必須重新安裝每個容量集區授權。如需其他詳細資料、請參閱重新安裝容量集區授權。

.相關資訊
* link:task_install_deploy.html["安裝ONTAP Select 部署功能"]
* link:task_cli_migrate_deploy.html#restoring-the-deploy-configuration-data-to-the-new-virtual-machine["將部署組態資料還原至新的虛擬機器"]
* link:task_adm_licenses.html#reinstalling-a-capacity-pool-license["重新安裝容量資源池授權"]

