---
sidebar: sidebar 
permalink: task_vpi_deploy_cluster.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, deploy cluster, deploying cluster, create cluster, creating cluster 
summary: 您可以透過vSphere Web使用者介面使用部署vCenter外掛程式來部署ONTAP Select VMware叢集。 
---
= 部署ONTAP Select 一個叢集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以透過vSphere Web使用者介面使用部署vCenter外掛程式來部署ONTAP Select VMware叢集。



== 開始之前

部署ONTAP Select VMware叢集之前、您應該先準備好使用部署vCenter外掛程式。



=== 所有規模叢集的通用準備

無論叢集大小為何、您都需要採取幾個步驟：

* 請閱讀「使用入門」一節、以熟悉部署vCenter外掛程式。
* 確保ONTAP Select 安裝並執行了「整合管理公用程式」。
* 安裝部署vCenter外掛程式。
* 準備Hypervisor主機或ONTAP Select 執行此叢集的主機。
* 取得叢集中節點所需的儲存授權檔案。
* 取得下列帳戶的認證資料：
+
** 部署系統管理員帳戶
** 可存取外掛程式的vCenter帳戶


* 如有需要、請在Windows憑證管理程式上、將部署SSL憑證安裝為「信任的根憑證授權單位」。
* 確認部署公用程式可透過網路存取vCenter伺服器的連接埠443。




=== 多節點叢集的其他準備工作

除了一般準備之外、您還應該熟悉部署網路檢查程式、然後再部署多節點叢集。



== 新增 Hypervisor 主機

您可以將Hypervisor主機新增至部署公用程式、ONTAP Select 以便在部署叢集之前執行各個節點。如果需要、您可以改為將主機新增為叢集建立對話框的一部分。

.開始之前
您應該檢閱「準備部署ONTAP Select 一個叢集」。

.關於這項工作
您可以根據叢集大小新增一或多個主機。

.步驟
. 使用瀏覽器透過vSphere HTML5登入vCenter伺服器。
. 在工具列中、按一下「*功能表*」、然後按一下「*全域庫存清單*」。
. 在左側窗格中、按一下「* ONTAP Select 」「*」「*」「部署*」、然後按一下「*主機*」索引標籤。
. 按一下右側的*「Add*」。
. 提供主機的主機名稱或IP位址、然後按一下「*新增*」或「*新增及結束*」。




== 建立單節點叢集

您可以透過vSphere Web用戶端使用VMware vCenter外掛程式來部署ONTAP Select 由單一節點組成的VMware叢集。

.開始之前
您應該檢閱「準備部署ONTAP Select 一個不支援的叢集並新增Hypervisor主機」。您可以在ONTAP Select 建立叢集之前或建立單節點叢集時、新增執行此節點的主機。

.步驟
. 使用瀏覽器透過vSphere HTML5登入vCenter伺服器。
. 按一下頂端的*功能表*、然後按一下*全域庫存清單*。
. 按ONTAP Select 一下左側窗格中的「*」「*「叢集*」、然後按一下「*新ONTAP Select 增*」。
+
如果您先前尚未接受SSL憑證、請按一下警告訊息中的IP連結、然後接受該憑證。然後返回vCenter頁面、按一下警告訊息中的連結以重新載入頁面。

. 在「*新ONTAP Select 版S編*」頁面上、輸入叢集詳細資料、然後按一下「*完成*」。
. 在「*節點設定*」區段中、提供組態並選取授權。
+
您可以變更預設節點名稱、並視需要上傳新的授權。

. 在* Hypervisor和網路*區段中、選取執行個體類型、主機和網路。
+
您可以視需要新增主機。節點的授權必須符合或超過執行個體類型。

. 在「*儲存設備*」區段中、選取儲存容量和儲存資源池。
+
您可以選擇在使用優質授權時啟用軟體RAID。

. 按一下「*完成*」、然後檢閱叢集的組態。
+
您可以視需要在每個區段中按一下「Edit（編輯）」來變更組態。

. 單擊 * 下一步 * 。
. 提供ONTAP 管理員密碼、然後按一下「*建立叢集*」開始建立叢集程序、然後在確認快顯視窗中按一下「*確定*」。
+
建立叢集可能需要30分鐘的時間。

. 重新整理頁面並選取新的叢集、然後按一下*摘要*和*詳細資料*來監控多步驟叢集建立程序。
+

TIP: 如果叢集建立作業已啟動但無法完成、ONTAP 您定義的整套管理密碼將不會登錄。在這種情況下、您可以使用ONTAP Select 密碼「changeme123」和「admin」帳戶來存取該叢集的管理介面。



.完成後
* 確認ONTAP Select AutoSupport 已啟用此功能。
* 備份ONTAP Select 「不再部署」組態資料。




== 建立多節點叢集

您可以透過vSphere Web用戶端使用VMware vCenter外掛程式來部署ONTAP Select 由多個節點組成的VMware叢集。

.開始之前
您應該檢閱「準備部署ONTAP Select 一個不支援的叢集並新增Hypervisor主機」。您可以在ONTAP Select 建立叢集之前或建立多節點叢集時、新增執行不完整節點的主機。

.關於這項工作
由偶數個節點組成的一個支援多節點叢集。ONTAP Select節點一律以HA配對的形式連接。

.步驟
. 使用瀏覽器透過vSphere HTML5登入vCenter伺服器。
. 按一下頂端的*功能表*、然後按一下*全域庫存清單*。
. 按ONTAP Select 一下左側窗格中的「*」「*「叢集*」、然後按一下「*新ONTAP Select 增*」
+
如果您先前尚未接受SSL憑證、請按一下警告訊息中的IP連結、然後接受該憑證。然後返回vCenter頁面、按一下警告訊息中的連結以重新載入頁面。

. 在「*新ONTAP Select 版S編*」頁面上、輸入叢集詳細資料、然後按一下「*完成*」。
+
除非您有理由設定叢集MTU大小、否則您應該接受預設值、並允許部署視需要進行任何調整。

. 在「*節點設定*」區段中、提供HA配對中兩個節點的組態和選取授權。
+
您可以視需要變更預設節點名稱、並上傳新授權。

. 在「* Hypervisor與網路*」區段中、選取每個節點的執行個體類型、主機和網路。
+
您可以視需要新增主機。您必須選取三個網路。內部網路不能與管理或資料網路相同。節點的授權必須符合或超過執行個體類型。

. 在「*儲存設備*」區段中、選取儲存容量和儲存資源池。
+
您可以選擇在使用優質授權時啟用軟體RAID。

. 如果叢集有四個以上的節點、您必須依照第一個HA配對所使用的相同步驟、在其他HA配對中設定節點。
. 按一下「*完成*」、然後檢閱叢集的組態。
+
您可以視需要按一下每個區段中的*編輯*來變更組態。

. 或者、執行網路連線檢查程式、以測試內部叢集網路上節點之間的連線能力。
. 單擊 * 下一步 * 。
. 提供ONTAP 管理員密碼、然後按一下「*建立叢集*」開始建立叢集程序、然後在確認快顯視窗中按一下「*確定*」。
+
建立叢集可能需要30分鐘的時間。

. 重新整理頁面並選取新的叢集、然後按一下*摘要*和*詳細資料*來監控多步驟叢集建立程序。
+

TIP: 如果叢集建立作業已啟動但無法完成、ONTAP 您定義的整套管理密碼將不會登錄。在這種情況下、您可以使用ONTAP Select 密碼「changeme123」和「admin」帳戶來存取該叢集的管理介面。



.完成後
* 確認ONTAP Select AutoSupport 已啟用此功能。
* 備份ONTAP Select 「不再部署」組態資料。

