---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: 如果由於某種原因而導致無法使用此功能、您將無法管理節點和叢集。ONTAP Select ONTAP Select此外、所有雙節點叢集都會喪失HA功能、因為部署所包含的中介服務無法使用。如果發生不可恢復的故障、您必須恢復部署公用程式執行個體、才能還原管理和HA功能。 
---
= 恢復雙節點叢集的 ONTAP Select 部署公用程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果由於某種原因而導致無法使用此功能、您將無法管理節點和叢集。ONTAP Select ONTAP Select此外、所有雙節點叢集都會喪失HA功能、因為部署所包含的中介服務無法使用。如果發生不可恢復的故障、您必須恢復部署公用程式執行個體、才能還原管理和HA功能。



== 準備恢復部​​署實用程式

在嘗試還原 Deploy 實用程式實例之前，您需要做好準備以確保成功。您必須熟悉若干行政程序並掌握所需資訊。

.步驟
. 確認您可以在虛擬機器管理程式環境中安裝ONTAP Select Deploy 實用程式的新實例。
+
link:task_install_deploy.html["了解如何安裝ONTAP Select Deploy 實用程式"]

. 確認您可以登入ONTAP Select叢集並存取ONTAP叢集 shell (CLI)。
. 確定您是否擁有包含ONTAP Select雙節點叢集的失敗部署公用程式實例的設定資料備份。您可能擁有不包含該叢集的備份。
. 根據所使用的復原程序，驗證是否可以還原部署配置資料的備份。
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["了解如何將部署配置資料還原到新的虛擬機"]

. 您擁有發生故障的原始部署公用程式虛擬機器的 IP 位址。
. 確定採用容量池許可或容量層級許可。如果使用容量池許可，則必須在復原或還原 Deploy 執行個體後重新安裝每個容量池許可證。
. 決定在復原ONTAP Select Deploy 實用程式實例時使用哪個程式。您的決定取決於您是否擁有包含ONTAP Select雙節點叢集的原始故障 Deploy 實用程式的設定資料備份。
+
[cols="35,65"]
|===
| 您是否有包含雙節點叢集的部署備份？ | 使用恢復程序… 


| 是的 | <<restore-deploy-backup,使用組態備份還原部署公用程式執行個體>> 


| 否 | <<restore-and-recover-deploy,重新設定及恢復部署公用程式執行個體>> 
|===




== 使用組態備份還原部署公用程式執行個體

如果您有包含雙節點叢集的失敗部署公用程式執行個體備份、您可以將組態資料還原至新的部署虛擬機器執行個體。然後、您必須執行ONTAP Select 額外的組態來完成恢復、將兩個節點放在一個叢集內。

.開始之前
備份包含雙節點叢集的原始部署失敗虛擬機器的設定資料。您必須能夠登入雙節點叢集的ONTAP CLI，並且知道這兩個節點的ONTAP名稱。

.關於這項工作
由於還原的組態備份包含雙節點叢集、因此在新的部署公用程式虛擬機器中、會重新建立協調器iSCSI目標和信箱。

.步驟
. 準備ONTAP Select 一套全新的示例的示例：
+
.. 安裝新的部署公用程式虛擬機器。
.. 將部署組態從先前的備份還原至新的虛擬機器。
+
如需安裝與還原程序的詳細資訊、請參閱相關工作。



. 登入ONTAP 到位在現象雙節點叢集的指令行介面。ONTAP Select
. 進入進階權限模式：
+
[source, cli]
----
set adv
----
. 如果新部署虛擬機器的 IP 位址與原部署虛擬機器的 IP 位址不同，請刪除舊的中介 iSCSI 目標並新增目標：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
「<ip_address>'參數是新部署虛擬機器的IP位址。

+
這些命令可讓ONTAP Select 各個節點探索新部署公用程式虛擬機器上的信箱磁碟。

. 確定中介磁碟的名稱：
+
[source, cli]
----
disk show -container-type mediator
----
. 將信箱磁碟指派給兩個節點：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 確認已啟用儲存容錯移轉：
+
[source, cli]
----
storage failover show
----


.完成後
如果您使用容量池許可，請重新安裝每個容量池許可證。看link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安裝 Capacity Pool 授權"]更多詳情請見下文。



== 重新設定及恢復部署公用程式執行個體

如果您沒有包含雙節點叢集的失敗部署公用程式實例的備份，請在新的部署虛擬機器中設定中介 iSCSI 目標和郵件信箱。然後，透過對ONTAP Select叢集中的兩個節點進行額外配置來完成復原。

.開始之前
請確認您已取得新部署公用程式實例的中介目標名稱。您必須能夠登入雙節點叢集的ONTAP CLI，並且知道這兩個節點的ONTAP名稱。

.關於這項工作
您可以選擇性地將組態備份還原至新的部署虛擬機器、即使該虛擬機器不包含雙節點叢集。由於雙節點叢集並非以還原方式重新建立、因此您必須透過ONTAP Select 部署的「支援資訊」線上文件網頁、將中介iSCSI目標和信箱手動新增至新的部署公用程式執行個體。您必須能夠登入雙節點叢集、並知道ONTAP 兩個節點的名稱。


NOTE: 恢復程序的目標是將雙節點叢集還原至正常狀態、以便執行正常的HA接管和恢復作業。

.步驟
. 準備ONTAP Select 一套全新的示例的示例：
+
.. 安裝新的部署公用程式虛擬機器。
.. （可選）將部署組態從先前的備份還原至新的虛擬機器。
+
如果還原先前的備份、新的部署執行個體將不會包含雙節點叢集。如需安裝與還原程序的詳細資訊、請參閱相關資訊一節。



. 登入ONTAP 到位在現象雙節點叢集的指令行介面。ONTAP Select
. 進入進階權限模式：
+
[source, cli]
----
set adv
----
. 取得中介iSCSI目標名稱：
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. 存取新部署公用程式虛擬機器的線上文件網頁、然後使用admin帳戶登入：
+
http://<ip_address>/api/ui`

+
您必須使用部署虛擬機器的IP位址。

. 選擇 *Mediator*，然後選擇 *GET /mediators*。
. 選擇「試用！」以顯示 Deploy 維護的中介器清單。
+
記下所需中介執行個體的ID。

. 選擇“中介者”，然後選擇“POST”。
. 請提供「中介人ID的值。
. 選擇旁邊的“型號” `iscsi_target`並填寫名稱值。
+
使用iqn_name參數的目標名稱。

. 選擇「試用！」以建立中介 iSCSI 目標。
+
如果申請成功、您將會收到HTTP狀態代碼200。

. 如果新部署虛擬機器的IP位址與原始部署虛擬機器不同、您必須使用ONTAP CLI移除舊的中介iSCSI目標、並新增新目標：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
「<ip_address>'參數是新部署虛擬機器的IP位址。

+
這些命令可讓ONTAP Select 各個節點探索新部署公用程式虛擬機器上的信箱磁碟。

. 確定中介磁碟的名稱：
+
[source, cli]
----
disk show -container-type mediator
----
. 將信箱磁碟指派給兩個節點：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 確認已啟用儲存容錯移轉：
+
[source, cli]
----
storage failover show
----


.完成後
如果您使用容量池許可，請重新安裝每個容量池許可證。看link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安裝 Capacity Pool 授權"]更多詳情請見下文。
