---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: 您可以測試ONTAP Select 內部叢集網路上兩個或多個節點之間的網路連線能力。您通常會在部署多節點叢集之前執行此測試、以偵測可能導致作業失敗的問題。 
---
= 確認ONTAP Select 各個節點之間的網路連線能力
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以測試ONTAP Select 內部叢集網路上兩個或多個節點之間的網路連線能力。您通常會在部署多節點叢集之前執行此測試、以偵測可能導致作業失敗的問題。

.開始之前
測試中包含的所有ONTAP Select 支援節點都必須設定並開啟電源。

.關於這項工作
每次開始測試時、會在背景中建立新的程序執行、並指派唯一的執行識別碼。一次只能啟用一次掃描。

測試有兩種模式可控制其運作：

* 快速此模式會執行基本的不中斷測試。執行ping測試、並測試網路MTU大小和vSwitch。
* 延伸此模式會對所有的備援網路路徑執行更全面的測試。如果您在作用ONTAP Select 中的VMware叢集上執行此功能、叢集的效能可能會受到影響。



NOTE: 建議您在建立多節點叢集之前、一律先執行快速測試。快速測試成功完成後、您可以根據正式作業需求、選擇性地執行延伸測試。

.步驟
. 使用系統管理員帳戶登入部署公用程式CLI。
. 顯示網路連線檢查程式目前的執行、並確認沒有任何執行活動：
+
「網路連線檢查秀」

. 啟動網路連線檢查程式、並在命令輸出中記下執行識別碼：
+
「網路連線功能檢查start -host-names主機名稱-vswitch-type vSwitch_te-mode模式」

+
範例

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. 根據執行識別碼監控網路連線檢查的進度：
+
「網路連線功能檢查show -run、id run、ID」



.完成後
網路連線檢查程式通常會移除新增至ONTAP內部連接埠群組的任何暫用連接埠和IP位址、以清除網路連線。不過、如果連線檢查程式無法移除暫用連接埠、您必須重新執行CLI命令並使用「mode cleanup」選項來執行手動清除作業。如果您未從ONTAP內部連接埠群組移除暫用連接埠、ONTAP Select 可能無法成功建立該虛擬機器。
