---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: 您可以使用命令列介面、將現有的部署管理公用程式執行個體移轉至新的虛擬機器。 
---
= 將部署執行個體移轉至新的虛擬機器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用命令列介面、將現有的部署管理公用程式執行個體移轉至新的虛擬機器。

此程序的基礎是建立新的虛擬機器、使用原始虛擬機器的組態資料。新的和原始的虛擬機器必須執行相同版本的Deploy公用程式。您無法移轉至不同版本和版本的Deploy公用程式。



== 備份部署組態資料

在移轉虛擬機器時、您必須建立部署組態資料的備份。您也應該在部署ONTAP Select 完一個叢集後建立備份。資料會儲存至單一加密檔案、您可以下載到本機工作站。

請確定部署在備份作業期間未執行任何其他工作。

您建立的備份檔案會從虛擬機器擷取所有組態資料。此資料說明部署環境的各個層面、包括ONTAP Select 叢集。

.步驟
. 以系統管理員帳戶使用SSH登入部署公用程式CLI。
. 建立部署組態資料的備份、該資料儲存在部署伺服器的內部目錄中：
+
「部署備份建立」

. 出現提示時、請提供備份密碼。
+
備份檔案會根據密碼進行加密。

. 在系統中顯示可用的備份：
+
「部署備份顯示-詳細」

. 根據「*建立*」欄位中的日期選取備份檔案、並記錄*下載URL*值。
+
您可以透過URL存取備份檔案。

. 使用網頁瀏覽器或Curl等公用程式、將備份檔案下載到含有URL的本機工作站。




== 安裝部署虛擬機器的新執行個體

您必須建立新的部署虛擬機器執行個體、以便使用原始虛擬機器的組態資料進行更新。

您必須熟悉在ONTAP Select VMware環境中下載及部署VMware部署虛擬機器的程序。

這項工作的說明層級很高。

.步驟
. 建立部署虛擬機器的新執行個體：
+
.. 下載虛擬機器映像。
.. 部署虛擬機器並設定網路介面。
.. 使用SSH存取部署公用程式。




link:task_install_deploy.html["安裝ONTAP Select 部署功能"]



== 將部署組態資料還原至新的虛擬機器

您必須將組態資料從原始部署公用程式虛擬機器還原至新的虛擬機器。資料位於單一檔案中、您必須從本機工作站上傳。

您必須擁有先前備份的組態資料。資料包含在單一檔案中、必須可在本機工作站上使用。

.步驟
. 在本機工作站的命令Shell中、使用sftp公用程式將備份檔案上傳至部署虛擬機器。
+
範例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. 以系統管理員帳戶使用SSH登入部署公用程式CLI。
. 還原組態資料。
+
「部署備份還原-path pathname -fileName」

+
範例

+
「部署備份還原-path /home/admin -fileName deploy備份_20180601162151.tar .gz」


